### ISSUE TITLE
Support for FUSE / sshfs?

### ISSUE THREAD

**Issue by theronic** [passcod/cargo-watch#102]
Does cargo-watch work with FUSE-mounted file systems? Initial testing on Raspbian with a FUSE filesystem mounted from a remote OSX machine does not trigger a build.

**Comment by theronic** [comment]
Okay, I see that SSHFS does not implement the inotify protocol, so FUSE changes won't trigger `cargo-watch`. It's really hard to get something to auto-build on changes on a remote architecture without setting up cross-compiler toolchains.

Apparently it's possible to send change FUSE notifications from the server, but I don't know how. Maybe someone can chime in with a quickfix server-side.

**Comment by passcod** [comment]
I mean, it will work with polling enabled.

Also this (non-polling sshfs support) is something that will be possible in the future, because of improvements way down the stack, but I wouldn't hold my breath for anything happening before mid-2019.
