### ISSUE TITLE
Running arbitrary cargo commands

### ISSUE THREAD

**Issue by neuschaefer** [passcod/cargo-watch#11]
Sometimes I would like to run `cargo run` when the code changes.

How about changing the command line interface in the following way?
* Allow commands such as `cargo watch run --example foo1 bar baz` by simply running the appropriate cargo subcommand.
* Possibly remove direct options other than `--help`.

I don't know how to do this with `docopt`.

**Comment by ilkosta** [comment]
:+1:  +1 for the `run` integration.

**Comment by compressed** [comment]
I worked on this in PR https://github.com/passcod/cargo-watch/pull/18. Let me know if it works for you.
