### ISSUE TITLE
qemu serial to stdio not working when invoked from cargo-watch

### ISSUE THREAD

**Issue by dbeckwith** [passcod/cargo-watch#110]
I'm trying to run the command `qemu-system-x86_64 -drive format=raw,file=target/x86_64-snos/debug/bootimage-snos.bin -serial mon:stdio -device isa-debug-exit,iobase=0xf4,iosize=0x04` from `cargo-watch`. I can run the command just fine on its own from the shell or a script, but trying to invoke the command directly or through a script from `cargo-watch` causes it to hang and the emulator never launches. If I remove the `-serial mon:stdio` option, it runs fine, so something about QEMU mapping serial to `stdio` breaks when run from `cargo-watch`. Any idea why, or if it's fixable?

**Comment by passcod** [comment]
I suspect you'll get the same thing, but can you try under `watchexec`?

**Comment by passcod** [comment]
This is likely related to https://github.com/watchexec/watchexec/pull/47, which coincidentally got a pull request today! https://github.com/watchexec/watchexec/pull/102

If you can, could you try build that PR and running with watchexec to see if it also fixes your issue?

**Comment by dbeckwith** [comment]
Interesting, that sounds like it might be it. I'll try it out and let you know.

**Comment by dbeckwith** [comment]
Yep, that's it. I get the same issue with `watchexec` on `master`, but the branch from that PR works fine!

**Comment by passcod** [comment]
Oh, wonderful. Alright, I'll review that PR tonight and release a new watchexec and cargo-watch then.

**Comment by passcod** [comment]
Fixed in 7.0.9.
