### ISSUE TITLE
How to watch multiple folders

### ISSUE THREAD

**Issue by christiansakai** [passcod/cargo-watch#119]
Sorry if this has been described somewhere in the docs, but after searching and googling I couldn't find it.

Is there a way to watch multiple folders, lets say `templates` and `src`?

**Comment by passcod** [comment]
The way multiple arguments work in clap (and thus cargo watch) is to specify the option-value pair multiple times, like so:

    cargo watch -w templates -w src

**Comment by christiansakai** [comment]
Thank you so much for the quick response!
