### ISSUE TITLE
Show only first screen

### ISSUE THREAD

**Issue by vandenoever** [passcod/cargo-watch#122]
Working with `cargo watch` is great, but there's a lot of scrolling back to the first line of the output.

It would be great if the output would be limited to the first screen or if the output was piped to `less` to achieve that.

I've experimented with this but could not get this to work with current `cargo watch`. I can achieve the effect without colors like so:

```
cargo watch -s 'cargo check 2>&1 | fold -w $(tput cols) | head -$(($(tput lines)-1))
```

When using `cargo check --color always` the lines with color are shorter than 80 the terminal width because `fold` also counts the color codes.

**Comment by vandenoever** [comment]
I wrote a small application that can be combined with cargo watch to make it show one page with colors at a time:

```rust
use std::io::{self, Read, Write};

fn main() {
    let max_width = 80;
    let max_height = 115;

    let stdin = io::stdin();
    let mut handle = stdin.lock();
    let mut buffer = [0; 1];
    let mut escape = false;
    let mut pos = 0;
    let mut line = 0;

    while let Ok(n) = handle.read(&mut buffer) {
        if n == 0 {
            break;
        }
        let c = buffer[0];
        io::stdout().write(&buffer).unwrap();
        // an escaped sequence starts with escape (27) and ends with 'm'
        if c == 27 {
            escape = true;
        } else if escape && c == b'm' {
            escape = false;
        } else if !escape {
            if c == b'\n' {
                pos = 0;
                line += 1;
            } else {
                pos += 1;
                if pos == max_width {
                    io::stdout().write(&[b'\n']).unwrap();
                    pos = 0;
                    line += 1;
                }
            }
        }
        if line > max_height {
            break;
        }
    }
}
```
```bash
cargo watch --clear -s 'cargo check --color always 2>&1 | page_cat'
```

**Comment by passcod** [comment]
I personally use

```bash
cargo watch -s 'cargo check --color=always 2>&1 | less -RXE'
```

However making this generic is harder than it sounds! For instance this completely breaks when doing Windows cross-compiling from Linux, and there's other concerns with different platforms and colour encodings. I'm also not interested in replicating the large amount of things `less` does.

**Comment by vandenoever** [comment]
I tried using `less`. Getting that to work would be cleanest.
```
cargo watch -s 'cargo check --color=always 2>&1 | less -RXE'
```
gives me no output at all. This is on Konsole. and on XTerm. Piping to cat or the above page_cat does work.

Perphaps there's an environment variable or argument that is not being passed.

**Comment by passcod** [comment]
Try with `less -R` ? That should at least work. It does the same as what
page_cat does, but with less. `XE` are just niceties.

**Comment by vandenoever** [comment]
I've now updated `cargo watch` from 7.0.7 (from last october) to 7.2. And that works.

Thanks you for your help.
