### ISSUE TITLE
Keep order of commands to execute

### ISSUE THREAD

**Issue by AndiDog** [passcod/cargo-watch#124]
```
$ cargo watch -s '~/bin/clear-my-terminal' -x run
[Running 'cargo run && ~/bin/clear-my-terminal']
...
```

This is against expectation and screws up my use case of clearing the scrollback and content of my terminal before showing Rust build output. `-x`/`-s` order should be preserved.

**Comment by passcod** [comment]
(This is documented in the help message.)

We can't do this, because clap (argument parser) doesn't support this. See #77.
