### ISSUE TITLE
Forward termination signal to child process on Windows

### ISSUE THREAD

**Issue by Boscop** [passcod/cargo-watch#126]
When using the `ctrlc` crate to intercept Ctrl-C it doesn't work when running my exe through `cargo watch -x run` (my ctrlc handler won't get executed).

https://github.com/rust-lang/cargo/issues/4575

**Comment by Boscop** [comment]
@passcod Could you please look into this? It's very important.
Cargo does it now, so the implementation should be pretty much copy-paste: https://github.com/rust-lang/cargo/issues/4575

**Comment by passcod** [comment]
I don't have a Windows machine at the moment but if you want to put together a PR I'll merge and release ASAP







---- On Wed, 06 Jan 2021 14:36:45 +1300 Boscop <notifications@github.com> wrote ----





https://github.com/passcod Could you please look into this? It's very important.
 Cargo does it now, so the implementation should be pretty much copy-paste: https://github.com/rust-lang/cargo/issues/4575

**Comment by passcod** [comment]
Closing here, please file on upstream if it's still an issue.
