### ISSUE TITLE
Dedicated ignore file

### ISSUE THREAD

**Issue by justanotherdot** [passcod/cargo-watch#127]
Hi there!

`ripgrep` uses an `.ignore` file as well as a `ripgrep`-specific ignore file `.rgignore` in addition to the `.gitignore` for filtering out files to focus on. I'm currently using the ignore functionality but I would like to encode this as part of projects so others can benefit from the ignore but can't easily add it to the `.gitignore` since we need to commit a portion of the ignored files to version control. How hard would this be to add? 

Thanks for the great tool!

**Comment by passcod** [comment]
Probably pretty easy. Would this be only respecting `.ignore` as well as `.gitignore`, or would we also want a `.cargowatchignore` (or `.cwignore` or something)?

**Comment by justanotherdot** [comment]
I feel like `.ignore` has some history with sharing across other tooling like `fd` and `ripgrep` which might be helpful if you want all tools to share them? Otherwise, the advantage of having a dedicated `.cargowatchignore` or `.cwignore` is chiefly that we can explicitly ensure that the watch doesn't loop because of temporary files generated by a test, for example (my case, actually).

I could try to make the patch if you'd like the hand?

**Comment by passcod** [comment]
If you can, that would be ace :)

**Comment by justanotherdot** [comment]
Sure thing, any guidance on how to get started specifically? I'll try cloning and looking around sometime next week in my spare time.

**Comment by passcod** [comment]
This will need upstream support, so you'll want to look at watchexec (where I'm also a maintainer!) first. Look at the `watch()` function in `run.rs`, that's where the .gitignore is loaded. The current interface only has a boolean (`true` to load .gitignore), that should probably be changed to some other structure to allow more than just that to be loaded. One idea would be a `Vec<OsString>` and just load the file by that name, but whatever makes sense.

If you want to add support to the watchexec CLI interface, you'll need to edit the args and pick some argument scheme; don't feel obligated to, though. In any case, you'll then need to open a small PR here adding support for your new API in watchexec.

**Comment by justanotherdot** [comment]
Hi there! :wave: Sorry for the delay in getting up a PR.

The attached PR supports upstream by basically mimicking the `.gitignore` but making it distinct. This way you could specify a .ignore that would work across a family of tooling that isn't tied to what files you don't want checked into version control. 

Let me know what you think! Happy to make tweaks when the time presents itself.

**Comment by justanotherdot** [comment]
Haven't forgotten about this, just trying to find some time to get back to it. Last time I gave a go I didn't see a release upstream I could use at `watchexec` that included it, but I see there's a `1.11.1` release I might give a try.
