### ISSUE TITLE
"There is no `AsOsStr` in `std::ffi`" when building

### ISSUE THREAD

**Issue by galaux** [passcod/cargo-watch#13]
`cargo build` gives `There is no 'AsOsStr' in 'std::ffi'`:

```
cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading libc v0.1.5
 Downloading docopt v0.6.59
 Downloading regex v0.1.26
 Downloading time v0.1.24
 Downloading inotify v0.1.9
 Downloading rustc-serialize v0.3.12
 Downloading gcc v0.3.4
 Downloading docopt_macros v0.6.59
 Downloading notify v1.2.1
   Compiling inotify v0.1.9
   Compiling rustc-serialize v0.3.12
   Compiling time v0.1.24
error: invalid character `-` in crate name: `build-script-build`
error: invalid character `-` in crate name: `build-script-build`
error: aborting due to 2 previous errors
Build failed, waiting for other jobs to finish...
/home/miguel/.cargo/registry/src/github.com-1ecc6299db9ec823/inotify-0.1.9/src/wrapper.rs:23:5: 23:22 error: unresolved import `std::ffi::AsOsStr`. There is no `AsOsStr` in `std::ffi`
/home/miguel/.cargo/registry/src/github.com-1ecc6299db9ec823/inotify-0.1.9/src/wrapper.rs:23 use std::ffi::AsOsStr;
                                                                                                 ^~~~~~~~~~~~~~~~~
error: aborting due to previous error
error: invalid character `-` in crate name: `rustc-serialize`
error: aborting due to previous error
Could not compile `time`.
```

I am brand new on both Rust and Cargo but [it seems `AsOsStr` has vanished from latest Rust](https://doc.rust-lang.org/std/ffi/)

cargo 0.0.1-pre-nightly (66849de 2015-03-10) (built 2015-03-11)
rustc 1.0.0-dev (built 2015-04-27)

**Comment by passcod** [comment]
You're welcome to try to fix it (and I'll merge your changes gladly), but personally at this point I'm waiting until Rust stable to pick it up again seriously, so I'm probably not going to keep this updated to the nightly.

**Comment by galaux** [comment]
As far as I understand, I am not using the nightly build of rust: this is the 1.0.0-beta.3 which is I guess the only "stable" version available. So unless there is a more stable version available, then your – awesome – plugin can just NOT be built. Or am I missing a something?

**Comment by passcod** [comment]
Oh, sorry. No, I meant that I have put all of my Rust-based projects, months ago, on standby until Rust stable (not the beta) comes out. The timeline for this is [15th May](http://blog.rust-lang.org/2015/02/13/Final-1.0-timeline.html). So in two weeks I'll make this work with the stable, until then I rely on other people volunteering compatibility updates. Yes, it does mean that currently cargo watch cannot be built, sorry about that.

**Comment by galaux** [comment]
Ok. Thanks for the info.

**Comment by Detegr** [comment]
This issue is obsolete, cargo-watch now compiles with nightly.
