### ISSUE TITLE
Constantly re-runs command on osx

### ISSUE THREAD

**Issue by jamak** [passcod/cargo-watch#131]
Environment:
```
uname -a:
Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

rustup -Vv:
rustup 1.20.2 (13979c968 2019-10-16)

rustc -Vv:
rustc 1.38.0 (625451e37 2019-09-23)
binary: rustc
commit-hash: 625451e376bb2e5283fc4741caa0a3e8a2ca4d54
commit-date: 2019-09-23
host: x86_64-apple-darwin
release: 1.38.0
LLVM version: 9.0

cargo -Vv:
cargo 1.38.0 (23ef9a4ef 2019-08-20)
release: 1.38.0
commit-hash: 23ef9a4ef8a96d09b1fd67b2f4e023f416bb1ff1
commit-date: 2019-08-20
```

Issue: whenever I run cargo watch with any command, the command keeps being rerun. When I run with debug, I see a line that says 
`*** Paths updated: [PathOp { path: "/path/to/project/src", op: Some((empty)), cookie: None }]`
before each run. 

Here's an example output of a run (the command here was `cargo watch -w src/ -s "echo hi"  --debug --postpone`):

```
*** Paths updated: [PathOp { path: "/path/to/project/src", op: Some((empty)), cookie: None }]
[Running 'echo hi']
*** Sending SIGTERM (int: 15) to child process
*** Waiting for process to exit...
*** Launching child process
*** Assembled command "sh" "-c" "echo hi; echo [Finished running. Exit status: $?]"
*** Waiting for filesystem activity
hi
[Finished running. Exit status: 0]
*** Received SIGCHLD
```

^ That block above just repeats ad infinitum.

note that I didn't modify anything in that directory. I assume this is related to the latest fsevent release but I wanted to make an issue just in case.

**Comment by passcod** [comment]
Oops, sorry, misclicked.

When did you install cargo-watch? Was it from source/with cargo install or from a binary release?

**Comment by jamak** [comment]
It was with cargo install, a few months back. I recently reinstalled with
`cargo install --force cargo-watch`, but I'm reasonably certain that was
after the behavior started.


On October 18, 2019 at 12:10:52 AM, Félix Saparelli (
notifications@github.com) wrote:

Oops, sorry, misclicked.

When did you install cargo-watch? Was it from source/with cargo install or
from a binary release?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/passcod/cargo-watch/issues/131?email_source=notifications&email_token=AAAUBTFRSGA3TIDMYH3Y7M3QPEZMXA5CNFSM4JCBQHA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBSP5II#issuecomment-543489697>,
or unsubscribe

**Comment by passcod** [comment]
Hmm, I'll investigate; in the meantime could you try the binary release, see if that works? I'm not exactly expecting it to, mostly trying to reduce variables.

**Comment by RzvnB** [comment]
The same things happens on Windows 10 when running 'cargo watch -x run' but not when watching 'check' or 'build'. The command just keeps running itself no matter if you change the sources or not.

**Comment by jamak** [comment]
Now that I've restarted my machine, I haven't been able to reproduce this with any regularity. It has happened once or twice, (both with the binary release and from source), but I'm not sure it's a `cargo-watch` problem anymore.
