### ISSUE TITLE
cargo watch -x clippy runs slow

### ISSUE THREAD

**Issue by kanekv** [passcod/cargo-watch#136]
clippy invoked with `cargo watch -x clippy` is running much slower than by itself:

```
$ cargo clippy
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
```
vs
```
$ cargo watch -x clippy
[Running 'cargo clippy']
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
[Finished running. Exit status: 0]
[Running 'cargo clippy']
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Checking ....
    Finished dev [unoptimized + debuginfo] target(s) in 3.96s
[Finished running. Exit status: 0]
```

P.S. 2nd run just re-saving a file without any changes made.
It seems when running first time immediately after start it's fast, but on save it's painfully slow.

**Comment by passcod** [comment]
> Blocking waiting for file lock on package cache
> Blocking waiting for file lock on package cache

You probably have RLS or Rust Analyzer also running concurrently. See: https://github.com/passcod/cargo-watch#rls-is-slow-while-using-cargo-watch-or-vice-versa-or-its-waiting-for-the-project-lock-a-lot

**Comment by kanekv** [comment]
@passcod yeah, I tried without rls/ra_lsp now. I guess it's not a big of a problem at all, what I've noticed is that after you save file without making any changes cargo watch is still rebuilding something, while cargo clippy does not (not that it matters, as noone needs that use case working fast, just curious).
