### ISSUE TITLE
File creation/deletion triggers rebuild even if the file is ignored

### ISSUE THREAD

**Issue by dotdash** [passcod/cargo-watch#139]
At least on the Windows 10 machine I'm currently working on, the creation and deletion of vim swap files causes rebuilds, even though the files are ignored. It seems that the change on the directory (which is not ignored) is responsible for this:

    *** Ignoring "\\\\?\\C:\\Users\\bstei\\src\\klm\\src\\.responses.rs.swp": matched ignore filter
    *** Ignoring "\\\\?\\C:\\Users\\bstei\\src\\klm\\src\\.responses.rs.swp": matched ignore filter
    *** Paths updated: [PathOp { path: "\\\\?\\C:\\Users\\bstei\\src\\klm\\src", op: Some(WRITE), cookie: None }]
    [Running 'cargo run']

I don't recall seeing this on Linux, but I don't have access to a machine to test this on right now.

**Comment by passcod** [comment]
Hmm. I'm wondering for a good way of how that could be fixed, without (or with minimum) side effects:

- Ignoring writes for folders, may mean that adding a folder doesn't trigger.
- Ignoring writes for folders if no non-ignored file changes were seen previously in it... still has some edge cases, but is much harder to implement (need to keep complex state while watching).

**Comment by dotdash** [comment]
> Ignoring writes for folders, may mean that adding a folder doesn't trigger.

Looking at a debug trace, at least on Windows it seems that there's a dedicated type for creation/removal of a directory.

I'm seeing

    *** Paths updated: [PathOp { path: "\\\\?\\C:\\Users\\bstei\\src\\klm\\bla", op: Some(CREATE), cookie: None }]

and

    *** Paths updated: [PathOp { path: "\\\\?\\C:\\Users\\bstei\\src\\klm\\bla", op: Some(REMOVE), cookie: None }]

while the problematic event had a `Some(WRITE)` value for `op`. In which casses is a write event on a directory actually interesting?

**Comment by passcod** [comment]
Good point.

**Comment by rkfox** [comment]
I'm running a build.rs script that compresses folders in the project folder and writes the output folders to the .ignore file to prevent cargo watch from restarting when these files/folders get written. I have had a lot of issues with getting the .ignore to work properly, but it seems that I can get it working if I cargo run at least one time before running cargo watch to create the .ignore file. This isn't ideal; I'm wondering if it is possible to make cargo watch reload the .ignore file when the process restarts?

**Comment by passcod** [comment]
It's possible, but do you mind opening a separate feature request (on watchexec) so that gets tracked separately?

**Comment by rkfox** [comment]
Sure thing. I didn't know if I should start a new issue since this is essentially the same problem.

**Comment by jpaddison3** [comment]
I'm also getting this for sqlite .db-journal files, which are created and quickly destroyed. Their creation modifies the directory that they're in (which is not excluded from the watch), causing rebuilds on every write operation.

((Thanks for the tool, it's been very nice.))

**Comment by jpaddison3** [comment]
A workaround is to put them in a folder (eg `localdbs/dev.db`) and ignore the localdbs folder.

**Comment by passcod** [comment]
Closing in favour of upstream issue: https://github.com/watchexec/watchexec/issues/183.
