### ISSUE TITLE
Flag to watch the `lib` but not the `bin`

### ISSUE THREAD

**Issue by Lokathor** [passcod/cargo-watch#140]
I have a crate with both a lib and some bins.

I'd like the ability to set that `cargo watch` should watch the lib and rebuild it on change, but _not_ attempt to rebuild the bins while watching.

something like, `cargo watch -x build --lib`

**Comment by passcod** [comment]
Isn't that just `cargo watch -x 'build --lib'`? Or do you want it to do something more advanced?

**Comment by Lokathor** [comment]
Ohhhhh with quotes it works. Okay.
