### ISSUE TITLE
.git/info/exclude not respected

### ISSUE THREAD

**Issue by dbeckwith** [passcod/cargo-watch#142]
It seems like `cargo watch` does not respect files ignored by `.git/info/exclude` which can be annoying. I tend to ignore scratch files and editor-specific configs this way so my `.gitignore` files don't end up with a bunch of stuff specific to my system/setup, but it means that they trigger `cargo watch` when they are changed. I would expect `cargo watch` to ignore all files that are ignored by `git`, not just ones that are mentioned in the local `.gitignore`.

Example:
```
$ cargo watch --version
cargo-watch 7.3.0
$ cargo init . --vcs git --name test-crate
     Created binary (application) package
$ echo a > .gitignore
$ echo b > .git/info/exclude
$ git add .
$ git commit -m "Initial commit"
[master (root-commit) 535b929] Initial commit
 3 files changed, 13 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 Cargo.toml
 create mode 100644 src/main.rs
$ touch a b c
$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
    c

nothing added to commit but untracked files present (use "git add" to track)
$ cargo watch -s 'echo cargo watch triggered' &
[1] 24444
$ [Running 'echo cargo watch triggered']
cargo watch triggered
[Finished running. Exit status: 0]

$ touch a
$ touch b
$ [Running 'echo cargo watch triggered']
cargo watch triggered
[Finished running. Exit status: 0]

$ touch c
$ [Running 'echo cargo watch triggered']
cargo watch triggered
[Finished running. Exit status: 0]

$ 
```

Thanks for making this awesome tool! Let me know if there's anything more I can do to clarify. Would be willing to submit a PR as well if this seems like a good change to make.

**Comment by passcod** [comment]
Watchexec (our upstream) has a fairly limited view of ignore files and doesn't support all the git hierarchy at the moment. Contributions (there) accepted, though!

**Comment by passcod** [comment]
Closing in favour of upstream issue: https://github.com/watchexec/watchexec/issues/58.
