### ISSUE TITLE
"Cargo Watch" or "Cargo-Watch"?

### ISSUE THREAD

**Issue by JimLynchCodes** [passcod/cargo-watch#143]
Hi, this library is great, thanks!

Which command is correct here?

```
cargo watch -x test
```
or

```
cargo-watch -x test
```

They both seem to work for me... 🤔

**Comment by passcod** [comment]
If you want to use it as a standalone tool (second version), you can, but usually this is a cargo subcommand and so the first version is the most correct. It doesn't really matter. The _name_ (when writing/talking about it) is "Cargo Watch" without the hyphen.
