### ISSUE TITLE
Reload .ignore file when process restarts (feature request)

### ISSUE THREAD

**Issue by ghost** [passcod/cargo-watch#144]
I'm running a build.rs script that compresses folders in the project folder and writes the output folders to the .ignore file to prevent cargo watch from restarting when these files/folders get written. I have had a lot of issues with getting the .ignore to work properly, but it seems that I can get it working if I cargo run at least one time before running cargo watch to create the .ignore file. This isn't ideal; I'm wondering if it is possible to make cargo watch reload the .ignore file when the process restarts?

_Originally posted by @rkfox in https://github.com/passcod/cargo-watch/issues/139#issuecomment-626105735_

**Comment by rkfox** [comment]
I read over my post and realized it might be simpler and make more sense for cargo watch to watch the .ignore file for changes and reload only the .ignore file instead of doing a whole program restart.

**Comment by rkfox** [comment]
I have been looking over how build.rs watches for changes to the directory using the "include" and "exclude" directives inside of Cargo.tml. This could be a way to watch the .ignore file if implemented in cargo-watch.

**Comment by passcod** [comment]
Closing in favour of upstream issue: https://github.com/watchexec/watchexec/issues/187.
