### ISSUE TITLE
Bug with Unix sockets

### ISSUE THREAD

**Issue by ghost** [passcod/cargo-watch#145]
I have an actix_web server that uses "bind_uds" to listen on a Unix socket. In debug mode, the UNIX socket that actix creates gets deleted after the first connection to the server. The cargo watch and my application does not restart or issue any errors, but the socket file gets deleted.

This works fine:
cargo run
cargo run --release
cargo watch -x "run --release"

This does not:
cargo watch -x run

**Comment by passcod** [comment]
As clarification: Is your expectation that the unix socket file being deleted should trigger cargo-watch to restart? Or something else?
