### ISSUE TITLE
.gitignore in subfolders not honored

### ISSUE THREAD

**Issue by l0calh05t** [passcod/cargo-watch#147]
Cargo watch does not appear to honor `.gitignore` files in subfolders. For example, I have two folders that should be checked in and out as empty which contain the following `.gitignore`:

```
*
!.gitignore
```

I.e., everything except the `.gitignore` itself should be ignored. However, changes in these folders cause cargo-watch to trigger a build.

I am using cargo-watch 7.3.0 (and systemfd 0.3.0 in case it matters) on Windows 10.

**Comment by passcod** [comment]
That is known, yes. Neither does watchexec, which is our upstream on this. I'd love to eventually support this, of course, both for gitignores and for the other ignore file(s)... contributions are very welcomed on this aspect.

**Comment by l0calh05t** [comment]
I just looked there, and there seems to be a pull request already: https://github.com/watchexec/watchexec/pull/147

**Comment by passcod** [comment]
Oh, that's right. I'm not particularly happy about the entire state of that part of watchexec... but I think I'll go merge that to at least provide something.
