### ISSUE TITLE
Homebrew tap

### ISSUE THREAD

**Issue by arzg** [passcod/cargo-watch#150]
Hi,

Thanks for cargo watch, I use it every day and find it very useful.

I use [Homebrew](https://brew.sh), and would find it convenient if I could use it to install cargo-watch. I believe that something like the following would work:

```ruby
# In Formula/cargo-watch.rb
class CargoWatch < Formula
  desc "Watches over your Cargo project's source"
  homepage "https://github.com/passcod/cargo-watch"
  url "https://github.com/passcod/cargo-watch/releases/download/v7.4.1/cargo-watch-v7.4.1-x86_64-apple-darwin.tar.xz"
  sha256 "insert hash here"
  version "7.4.1"

  def install
    bin.install "cargo-watch"
  end
end
```

**Comment by passcod** [comment]
You're welcome to do that. However, I do not do packaging. I'm happy to mention an existing packaging on the readme, I'm just not going to create nor make it the project's (i.e. my) responsibility to maintain.
