### ISSUE TITLE
Allow `cargo watch --features my_feature`

### ISSUE THREAD

**Issue by mulimoen** [passcod/cargo-watch#151]
Occasionally I want to write code which is behind a feature flag, using `cargo watch` to continuously check for compilation errors. It would be nice if `--features` could apply to `cargo check`, where the feature is enabled, thus checking the code just modified.

The current workaround I use is
```sh
cargo watch -x "check --features my_feature"
```

**Comment by passcod** [comment]
I'm a bit wary of anything that requires parsing user input, which this would as in `run -- --args` would need to become `run --features my_feature -- --args`. However, that doesn't seem bad, so I'm gonna say that's probably okay to implement.

**Comment by passcod** [comment]
### :1234: :question: Implementation steps:

1. Add the option to the cargo-watch args. This needs to accept the same syntax as cargo does, and have an appropriate help message.
2. For every `-x` input, parse to find the first `--` if any, and insert the features option before it. Alternatively, parse for the first word, and insert the option right after that. The latter is probably preferable as it would allow for individual commands to override (by virtue of their options coming later).
3. Add it to readme.
