### ISSUE TITLE
How to unignore only one specific file that is in .gitignore?

### ISSUE THREAD

**Issue by Boscop** [passcod/cargo-watch#153]
How to unignore only one specific file that is in .gitignore?

I find myself needing this a lot (when editing a config file), but `--no-gitignore` would unignore ALL files in `.gitignore`, which is not what I want because the other files also get modified but those shouldn't trigger a restart.

**Comment by passcod** [comment]
There's no way to do this at the moment.

**Comment by passcod** [comment]
Do you have an idea of what this could look like, options-wise?

One possible UI idea would be to have `--watch FILE` be more powerful than ignores.

**Comment by Boscop** [comment]
> One possible UI idea would be to have --watch FILE be more powerful than ignores.
@passcod Yeah, I think that would make the most sense. There is no way to be surprised by that behavior: Someone who passes `--watch` for a file without knowing that the file is in `.gitignore` won't be surprised when a change to the file causes a restart. And it's also the most intuitive to try `--watch` explicitly for gitignored files.

**Comment by passcod** [comment]
The question that remains is whether `--watch` should always be strictly more powerful than ignores, or only if it's passed a file rather than a directory. I'm leaning towards the latter, as I think I'd expect a watched folder's contents to still be matched against the ignores.

**Comment by Boscop** [comment]
@passcod I agree, makes perfect sense.

**Comment by passcod** [comment]
Closing in favour of upstream issue: https://github.com/watchexec/watchexec/issues/166.
