### ISSUE TITLE
Slow startup time for `cargo watch -x run`?

### ISSUE THREAD

**Issue by DarrenTsung** [passcod/cargo-watch#154]
Hi, thanks for the cool project. I'm using `cargo watch` to rebuild my server whenever my app starts up, but it takes a really long time for the watcher to start up.

Here's the truncated logs:
```
root@bd89e931d176:/app# cargo watch --debug -x run
2020-07-18T16:03:00.476+00:00 - DEBUG - Load Git/VCS ignores: true
...
2020-07-18T16:03:04.721+00:00 - DEBUG - Looking in "/" for a .git directory
...
2020-07-18T16:03:04.722+00:00 - DEBUG - built glob set; 0 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 13 regexes
2020-07-18T16:03:17.455+00:00 - DEBUG - Watching "/app"
...
2020-07-18T16:03:17.456+00:00 - DEBUG - Waiting for filesystem activity
...
```

I started running the command at `16:03:00`, and it doesn't start running the command until `16:03:17` - 17 seconds later! I'm using this for a small side-project so it's not like the project is particularly complicated or has a large amount of files to watch (tokei reports only 13 Rust files and 2.5k lines of code).

Do you have any recommendations on how to speed this up?

The full logs are here: https://gist.github.com/DarrenTsung/094d5a85ebea1caf694d2b09e0c7171c.

---

As an alternative I'm switching to using `entr` (https://jvns.ca/blog/2020/06/28/entr/), the replacement command would look something like:
```
find . -name *.rs | entr -r cargo run
```

However, `find . -name *.rs` is a bit slow:
```
root@eb54a79b4873:/app# time find . -name *.rs > /dev/null

real	0m5.749s
user	0m0.037s
sys	0m0.466s
```

I switched over to using ripgrep (installed ripgrep in the Dockerfile) and it's much faster:
```
root@eb54a79b4873:/app# time rg --type rust -g '!target' --files . > /dev/null

real	0m0.037s
user	0m0.055s
sys	0m0.009s
```

I needed to install `entr` from source because of a weird Docker for Mac file-notify bug, but the end result is a Dockerfile that looks like this (for anyone who might benefit from this in the future):
```
FROM rust:1.45

RUN apt-get update && apt-get install -y ripgrep

# Install entr from source (4.6), required for Docker for Mac workaround
# https://github.com/eradman/entr#docker-and-windows-subsystem-for-linux
RUN wget -c https://github.com/eradman/entr/archive/4.6.tar.gz -O - | tar -xz && cd entr-4.6 && ./configure && make install

# See: https://jvns.ca/blog/2020/06/28/entr/, https://github.com/eradman/entr#man-page-examples for some context, examples.
#
# rg --type rust -g '!target' --files .     : gets all the Rust files in the app directory.
# find . -type d                            : gets all directories (important to watch empty directories, 
#                                             otherwise entr will not notice if you add a new directory and 
#                                             then a new file in that directory).
#
# ENTR_INOTIFY_WORKAROUND=1                 : used to get around Docker for Mac issue: https://github.com/eradman/entr/issues/3.
RUN echo "while true; do { rg --type rust -g '!target' --files .; find . -type d; } | ENTR_INOTIFY_WORKAROUND=1 entr -dr cargo run; done" > /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /app

ENTRYPOINT /entrypoint.sh
```

The extra setup is kind of annoying to work through and maintain - I would definitely prefer for something like `cargo watch` handling adding new files, etc. but not at the cost of ~15 seconds whenever my container restarts.

**Comment by passcod** [comment]
Docker is generally iffy, Docker for Mac... that would depend on how the volume setup is done, I have no idea how this actually works, but as a wild guess, if it's a host mounted volume that is over, say, NFS or something, then this will be havoc.

I'm going to assume this is for development (please don't use cargo watch for production), and the advice there is to run the watcher *outside* (on the Mac side) and trigger (send a signal via docker kill or something) the action to the inside.
