### ISSUE TITLE
"--ignore data" not working?

### ISSUE THREAD

**Issue by vn971** [passcod/cargo-watch#155]
Hi, thanks for the awesome project! I seem to experience one very strange bug. If I run this command:
```sh
cargo watch --ignore docs -s date
```
Then it behaves correctly, e.g. it re-runs the command (`date` to print something) when I edit `src/main.rs`

However, when I run this command:
```sh
cargo watch --ignore data -s date
```
cargo watch stops executing anything on any changes at all, including when I change `/src/main.rs`

I've made a minimal reproducible example here:
https://gitlab.memri.io/memri/cargo-watch-bug-report
In the project, `data` and `docs` are defined almost identically, yet their behavior differs. Any clues on where this bug might come frome? Why is `data` so special?

I'm running version 0.7.5 on ArchLinux, rustc version 1.45.0, rustup version 1.22.1

**Comment by passcod** [comment]
Can't reproduce from your example on any of my machines, so probably something environmental.

**Comment by passcod** [comment]
Can you provide a debug log in both situations?

**Comment by vn971** [comment]
@passcod sorry for the slow reply. Debug log helped understand the problem indeed.

Apparently, the source of the difference is that the whole project lives inside a directory name that is exactly what I asked to ignore ("data" on my computer).

I wonder if `cargo watch` should match the *relative path* to decide on whether it's a match, or the absolute path. What do you think? Considering the fact that `cargo watch` intentially only works in a subdirectory, I guess there's case for using relative paths.

Thoughts? I'm regardless happy that I solved my problem and I know a work-around now, but I'm thinking whether we can improve the situation for others here

**Comment by passcod** [comment]
Yeah, the whole ignore thing needs redoing, for this and many other issues. [However](https://github.com/passcod/cargo-watch#troubleshooting):

> Please note that this project (and its upstream, watchexec)'s maintainership is at a low. Response to issues is on a best-effort basis only. Feature and improvement work is stalled indefinitely. Pull requests will be reviewed and merged as time allows. If you wish to take on more active maintainership, even for a limited time, enquire within (open an issue or send me mail).
