### ISSUE TITLE
Question: cargo watch -x run -s some_command does not execute "some_command"

### ISSUE THREAD

**Issue by apiraino** [passcod/cargo-watch#156]
Hi,

I was experimenting with piping a `notify-send` command when the watched command finishes, like sending a notification to the desktop when a long build finishes instead of staring at the screen waiting :)

Examples:
this works `cargo watch -x check -s "notify-send <title> <body>"`
this works `cargo watch -x build -s "notify-send <title> <body>"`
this *does not* work `cargo watch -x run -s "notify-send <title> <body>"`

I assume it's because `cargo run` does not really have an exit status code until the Rust application exits, so the shell command is actually never executed. In my case the Rust application is a web server, so `cargo run` runs the server (not sure if this is relevant to the question).

I don't think this qualifies as anyone's bug, I was just curious if I could workaround this behaviour :-)

**Comment by passcod** [comment]
It is as you say. You could do this:

```
cargo watch -s 'cargo build' -s 'notify...' -s 'cargo run'
```

**Comment by apiraino** [comment]
ah right :facepalm:  I didn't think of concatenating shell commands :smile: 

works great, thank you!
