### ISSUE TITLE
[feature_request] Custom restart on `rs` or any other command

### ISSUE THREAD

**Issue by Himujjal** [passcod/cargo-watch#157]
Nodemon has an interesting feature which let you restart the command that is running without saving your file. All you had to do is switch to the terminal and type `rs` + `Enter`. It restarts the command automatically.

I wish this feature is implemented in Cargo watch. Switching back and forth to the code editor for restarting is trouble for lazy people like me! Lol

**Comment by passcod** [comment]
Duplicate of #123
