### ISSUE TITLE
Wrong behaviour on WSL2 (Windows Subsystem for Linux, Ubuntu 20.04)

### ISSUE THREAD

**Issue by Immortalin** [passcod/cargo-watch#158]
`j` is a hello world program that prints the string "Shell agnostic bookmarks/directory jumper"
Correct behaviour (with cargo run):
```
~/D/R/j> cargo run
   Compiling j v0.1.0 (/home/lin/Development/Rust/j)
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/j`
Shell agnostic bookmarks/directory jumper

```

Incorrect behaviour with cargo watch:
```
~/D/R/j> cargo watch
[Running 'cargo check']
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
[Finished running. Exit status: 0]
```

The program does not print and exits immediately

**Comment by passcod** [comment]
Cargo watch runs `cargo check` by default. You want `cargo watch -x run`. Note that it also tells you what it's running:

    [Running 'cargo check']

**Comment by passcod** [comment]
I'd be interested in knowing where you found out about cargo watch, and if it's that source that misled you into thinking this would run your program :)

**Comment by Immortalin** [comment]
I used it before when I was on Linux. However the command was in my shell's (fish) autocomplete so after using it once so I never ever had to type it again. So I have completely forgotten the exact command 😅
