### ISSUE TITLE
Add ability to specify exit code to quit watching

### ISSUE THREAD

**Issue by xixixao** [passcod/cargo-watch#161]
I am building a hot reloading solution using cargo-watch. I would like to have the ability to cleanly exit the whole setup. For this I would like to configure cargo-watch such that it stops running when the command returns a specific exit code. I imagine the API could be like:

```sh
cargo watch -s "some command" --exit-on 13
```

If `some comand` returns exit code 13 cargo watch will itself stop.

**Comment by passcod** [comment]
I'd accept a PR that implemented that.

**Comment by passcod** [comment]
Closing in favour of upstream issue: watchexec/watchexec#132.
