### ISSUE TITLE
Cargo watch --poll rebuilds continuously with WSL2

### ISSUE THREAD

**Issue by Diggsey** [passcod/cargo-watch#162]
I'm running `cargo watch` in WSL2 on windows 10. The project is located on my C drive, so I'm accessing it via the `/mnt/c/...` path inside WSL2.

File-system notifications do not work correctly in this scenario, so I'm using the `--poll` option to `cargo watch`. This sometimes works, but often it ends upt just building the project repeatedly, so `cargo check` is never able to finish.

I also have the environment variable `CARGO_TARGET_DIR=target-wsl` so that it does not conflict with my windows builds. I'm guessing that `cargo watch` is seeing changes to the `target-wsl` directory and rebuilding?

**Comment by passcod** [comment]
Ah, yep, you'll need to ignore it (it should be in your gitignore?)

**Comment by Diggsey** [comment]
That seemed to fix it, thanks!
