### ISSUE TITLE
`cargo watch` should read a configuration file for actions if present

### ISSUE THREAD

**Issue by daniel-vainsencher** [passcod/cargo-watch#163]
Context: I love cargo watch, and am currently invoking it as `cargo watch -x check -x fmt -x doc -x clippy -x run`. This is a bit of a handful to type, so I've saved that in a shell script, at the root for a project. I would prefer for cargo watch to just mean that, ideally in all my projects by default.

Proposal:
- Have `cargo watch`, when not explicitly told what to do, look for configuration before defaulting to `cargo watch -x check`.ml.
- Some sort of per-user config in the home directory could serve as a customizable default.
- If neither is present, we should fall back to the current default behavior.

**Comment by passcod** [comment]
There's cargo-make for that kind of thing.

**Comment by daniel-vainsencher** [comment]
Thanks for the suggestion, I'll have a look at cargo make!
