### ISSUE TITLE
How to restart long-running process when file changed?

### ISSUE THREAD

**Issue by ccll** [passcod/cargo-watch#19]
I'm writting a HTTP API server and use cargo-watch to auto re-compile, a simple 'cargo watch test run' does not restart the previous running process but try to start a new process of my program.

Is there any other way to achive the desired effect besides of patching cargo-watch?

**Comment by passcod** [comment]
If you find an elegant way of doing this, do share, otherwise I think that's Out of Scope. You might want to run only `cargo watch test` and include something in your test code to run/kill the server if you need it running separately for tests to run.
