### ISSUE TITLE
Fix lock behaviour

### ISSUE THREAD

**Issue by passcod** [passcod/cargo-watch#2]
Current behaviour: "Don't start compiles within 2 seconds of **start** of current compile."
Intended behaviour: "Don't start compiles while current one is running."

Might also want to:
- wait until watched directory has "settled";
- forbid compiles to run within N seconds of each other (end1 -> start2), to avoid compiling too often when in the habit of saving compulsively (configurable, behind a flag);

**Comment by kstep** [comment]
Do you need some help here? I can help you, but my further work will be based upon #6 and #8 (or at least #6, if you don't want to merge #8).

**Comment by passcod** [comment]
I would love some help!

But... currently my development computer is down for the count and I haven't managed to fix it or get a replacement so I can't test anything, publish changes and crates, and generally have access to my development tools. So everything will have to wait until this weekend, sorry.

**Comment by passcod** [comment]
I'll be able to work on this next weekend at the latest. Again, sorry for the delay.

**Comment by kstep** [comment]
NP. Actually I took a little break after a quite long streak. My vacation is over, so I don't have as much time of OS projects as I had.

**Comment by passcod** [comment]
Woo! I'm back in the land of the linux :) If you've got something for this, greatly appreciated, otherwise I'll probably pick it up later, say next month.
