### ISSUE TITLE
Watcher hanging when `benches` folder is not present

### ISSUE THREAD

**Issue by inre** [passcod/cargo-watch#20]
It's hanging on the line `let _ = watcher.watch(&p.join("benches"));`. There is no `benches` folder in my projects. OS X 10.11.

**Comment by passcod** [comment]
Until resolution, the obvious workaround is to create a `benches` folder

**Comment by passcod** [comment]
@inre Could you confirm whether this is still an issue?

**Comment by passcod** [comment]
Closing, if this is still an issue do reopen.
