### ISSUE TITLE
cannot compile because notify-v2.3.1 cannot be compiled.

### ISSUE THREAD

**Issue by ken-graham** [passcod/cargo-watch#21]
I have tried to get cargo-watch to work on my own and have had no luck.

I am new to rust, so forgive me if there is something obvious that I have missed.

I cloned cargo-watch and altered nothing:

    ken@ken-desktop:/share/development/rust/cargo-watch$ git status
    # On branch master
    nothing to commit (working directory clean)

and tried a default cargo build, even a release build, and still produced the same results:

    ...
    /home/ken/.cargo/registry/src/github.com-121aea75f9ef2ce2/notify-2.3.1/src/inotify/mod.rs:1:1: 1:37 error: can't find crate for `inotify_sys`
    /home/ken/.cargo/registry/src/github.com-121aea75f9ef2ce2/notify-2.3.1/src/inotify/mod.rs:1 extern crate inotify as inotify_sys;
                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    error: aborting due to previous error
    Could not compile `notify`.

**Comment by passcod** [comment]
Works for me on ArchLinux, fully up-to-date, with latest Rust stable:

```
rustc 1.3.0 (9a92aaf19 2015-09-15)                         
cargo 0.4.0-nightly (553b363 2015-08-03) (built 2015-08-02)
```

and all up-to-date from this repository, using `cargo build`.

Just in case, I'm going to update this repo's Cargo.lock with the latest library versions, especially as a new version of `notify` has just gone out. **But**:

- Could you give me the OS you're running this on? Including its version.
- What version of Rust and Cargo are you running? You can find out with `rustc -V` and `cargo -V`.
- Can you run `cargo update` prior to running build and report back?

Thank you.

**Comment by ken-graham** [comment]
I did a git pull and recompile with your changes with the same result.

I am running under Ubuntu with the 3.2.0-92 kernel.

Here is the git log you requested: 
: git log -n1 --pretty=oneline
d09bb1f9f17e60f202aa0633fdd52b4c0c7f2437 Update Cargo.lock

The error produced is the same.

Thanks.

**Comment by passcod** [comment]
Can you please provide Rust and Cargo versions.

**Comment by ken-graham** [comment]
I was able to compile under both cloud9 and nitrous virtual machines just fine, so the problem is on my end somehow.

The version of Rust and Cargo, are the "out of the box" versions, using what one gets from "rustup".
