### ISSUE TITLE
thread '<unnamed>' panicked at 'internal error: entered unreachable code', ../src/libstd/sync/mpsc/mod.rs:565

### ISSUE THREAD

**Issue by fritzsche** [passcod/cargo-watch#22]
Hi,
works on Linux (Ubuntu) but in in MacOS I get error (rustc 1.4.0 (8ab8581f6 2015-10-27)) :
"thread '<unnamed>' panicked at 'internal error: entered unreachable code', ../src/libstd/sync/mpsc/mod.rs:565"

I though this is fixed by:
https://github.com/rust-lang/rust/issues/29201
https://github.com/passcod/rsnotify/issues/33

I have updated Cargo.toml build dependencies like:
notify = { git = "https://github.com/passcod/rsnotify.git", rev = "5a48333dde58a01f68c1e6" } 
rebuild crate, but get the same issue...

Thanks, Thomas

**Comment by passcod** [comment]
passcod/rsnotify#33 was only for OS X afaik

**Comment by passcod** [comment]
Can you just use `notify = "^2.1"` as in current source, that should get the latest with the current Cargo.lock, your revision is technically same code and thus useless.

**Comment by passcod** [comment]
Can you also provide the exact steps you use to make this segfault?

**Comment by fritzsche** [comment]
I started by:
1) git clone ....
2) cargo build --release
3) cp build/[...]/cargo-watch /usr/local/bin
4) In project folder "cargo watch"
--> On file change I get the segfault on MacOs (but works in Ubuntu)

I searched in the net and found above issues:
  5) changed Cargo.toml to ensure notify contains the patch
notify = { git = "https://github.com/passcod/rsnotify.git", rev = "5a48333dde58a01f68c1e6" } 
5) cargo update
6) cargo build --release
7) cp build/[...]/  /usr/local/bin
8) In project folder "cargo watch"
--> On file change still segfault. :-(

I also tried with notify master, but no difference. I have in also deleted old versions of cargo-watch /usr/local/bin to make sure no old version is remaining, also I tried "cargo clean" in between.

Version: macos el capitan
Rustc: 1.4

I'm novice to rust, sorry if I made something wrong.

**Comment by passcod** [comment]
Moving discussion to passcod/rsnotify#33 as this seems to be an upstream issue.

**Comment by octplane** [comment]
@fritzsche can you verify that it is fixed, when building against:

```
notify = { git = "https://github.com/octplane/rsnotify.git", rev="5a9d08d94665b3d53f78f4a9aab2d9fa8e0d70f8" }
```

Thank you.

**Comment by fritzsche** [comment]
This commit fixed the issue for me.

**Comment by octplane** [comment]
Thank you @fritzsche . I am awaiting for peer reviews regarding the patch. I should land in rsnotify quickly. Thank you again for your report and validation!
