### ISSUE TITLE
Not compiling when module is saved

### ISSUE THREAD

**Issue by GTB3NW** [passcod/cargo-watch#26]
When I'm editing files in a module and click save my intentions are to compile, however rust-watch is not compiling. I have to go into lib.rs or a bin file and save before it compiles.

Is this intended functionality or a bug?

**Comment by passcod** [comment]
This is probably a bug, but can you expand a bit on it? What paths work or not, is it only working when you edit src/lib.rs or src/main.rs or also src/foo.rs? What OS and cargo watch version is this? Etc

**Comment by GTB3NW** [comment]
Okay here's a sample project setup so you can re-create.

It seems that if a module contains a module it wont compile the sub-module. Perhaps this is just bad setup on my part (In which case how should I be setting up the project?)

```
.
├── Cargo.lock
├── Cargo.toml
├── src
│   ├── lib.rs
│   └── test
│       ├── mod.rs
│       └── test2
│           └── mod.rs
```

lib.rs:

```
pub mod test;
```
test/mod.rs:

```
pub mod test2;
```

test/test2/mod.rs:

```
fn test() {
    println!("Hello!");
}
```

Saving in the module test compiles, but saving in test/test2 does not compile.

**Comment by passcod** [comment]
What OS is this?

**Comment by GTB3NW** [comment]
Linux, specifically the arch linux distro.

**Comment by passcod** [comment]
I'm sorry! I haven't had time to look at this! I'll have a look asap... which might not be immediately. Sorry :(

**Comment by GTB3NW** [comment]
No worries my friend. I'm happy if it gets fixed in the short term or the long run, it still gets fixed in the end :P

**Comment by passcod** [comment]
I've tested with the latest cargo-watch 3.0.3 (which shouldn't change anything from 3.0.2, as it's just a change to move from `crate = "*"` version specs to `crate = "^1.2.3"`), compiled under Rust 1.6, on Arch Linux, with all packages updated as of a few hours ago. Here's the directory tree for my test:

```
src
├── cargo.rs
├── compile.rs
├── ignore.rs
├── main.rs
├── sub
│   ├── dir
│   │   └── file.rs
│   └── file.rs
└── timelock.rs

2 directories, 7 files
```

In the test, I run `cargo watch` at the root of the directory, and then proceed to `touch` a file to trigger the compilation. It works at all levels. Specifically:

- `touch src/compile.rs` works
- `touch src/sub/file.rs` works
- `touch src/sub/dir/file.rs` works

So, from my perspective, unless I've misunderstood you, this is a Works For Me. Can you try again and confirm if it does or does not work for you?

**Comment by GTB3NW** [comment]
Running 3.0.2 on rust 1.6.

How are you defining your modules, will it only compile if it's public? I'm also defining mine within each parent module FYI. So lib.rs would define timelock, timelock would define the next submodule and so on.

**Comment by passcod** [comment]
That shouldn't matter. Cargo-watch has no concept of what rust is doing, it just watches files and runs child processes. You can have a file that is never actually referenced in your "real" source, and modifications to it will *still* trigger builds. That's actually what I did above. The files were empty, zero-length. I simply `touch`ed the files, which changes the file's `mtime` and triggers a `MODIFY` event in the inotify backend (this being linux). Cargo-watch is watching for such events within the `src` directory and any sub-directory and files, and runs child processes.

So "how you define `<anything at all>`" will never actually matter. If you do it wrong, **cargo** will (presumably) complain. Cargo-**watch** has no idea.

At this point, I'm pretty stumped. Maybe:

- Your editor is doing something weird and not saving some files properly. Try another (like vim) to see if that works. Also try to just `touch` the files.
- You're actually running out of inotify Watches, so cargo-watch is failing to watch more than one or two directory levels. This is a system-wide problem and not a bug in the software. See here for details and workarounds: https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
- **Cargo** is failing to compile, not cargo-**watch**. I doubt this is the case, but one never knows. Is there an error message? Can you paste a screenshot of what's happening, or not happening?

**Comment by passcod** [comment]
Just to check, I recreated your test structure as above:

```
~/V/A/foo> nvim Cargo.toml
~/V/A/foo> mkdir -p src/test/test2
~/V/A/foo> cat > src/lib.rs
pub mod test;
~/V/A/foo> cat > src/test/mod.rs
pub mod test2;
~/V/A/foo> cat > src/test/test2/mod.rs
fn test() {
    println!("Hello!");
}
```

Then tried building with cargo directly, which works fine, albeit with a warning, but that's nothing:

```
~/V/A/foo> cargo build
   Compiling notify v2.5.4 (file:///home/Videos/Aerial/foo)
src/test/test2/mod.rs:1:1: 3:2 warning: function is never used: `test`, #[warn(dead_code)] on by default
src/test/test2/mod.rs:1 fn test() {
src/test/test2/mod.rs:2     println!("Hello!");
src/test/test2/mod.rs:3 }
```

And finally I started cargo-watch:

```
~/V/A/foo> ~/code/rust/cargo-watch/target/debug/cargo-watch
```

which gives no output as it's starting, and left it running while I ran `touch src/test/test2/mod.rs` in another window pane, upon which cargo-watch immediately compiled and tested the project:

```
~/V/A/foo> ~/code/rust/cargo-watch/target/debug/cargo-watch
$ cargo build
   Compiling notify v2.5.4 (file:///home/Videos/Aerial/foo)
src/test/test2/mod.rs:1:1: 3:2 warning: function is never used: `test`, #[warn(dead_code)] on by default
src/test/test2/mod.rs:1 fn test() {
src/test/test2/mod.rs:2     println!("Hello!");
src/test/test2/mod.rs:3 }
-> exit code: 0

$ cargo test
   Compiling notify v2.5.4 (file:///home/Videos/Aerial/foo)
src/test/test2/mod.rs:1:1: 3:2 warning: function is never used: `test`, #[warn(dead_code)] on by default
src/test/test2/mod.rs:1 fn test() {
src/test/test2/mod.rs:2     println!("Hello!");
src/test/test2/mod.rs:3 }
     Running target/debug/notify-c1e05e41340b84ef

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests notify

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

-> exit code: 0
```

Warnings again, but everything works fine.

**Comment by GTB3NW** [comment]
You may be on to something with the inotify, I'm pretty sure I upped it in the past.

Could you add a check with a prompt if it is too low so others know what's up? I'll test now.

**Comment by passcod** [comment]
Not really, no. 1) The only reliable way to check for it is to hit it and catch the error, which I'll make an issue for (#27), and 2) there's no such thing as "too low" a value for this.

Well, silly small values are probably too low, but the default is reasonable, _that's why it's the default_. What value is "too low" is highly dependent on what _you_ are doing, what software and distro and activity and everything else.

I _can_ add a link to the guard wiki page in the Readme, though.

**Comment by GTB3NW** [comment]
It's working now, didn't change my value so I figure it's just inotify and how I'm using my computer at the time.
