### ISSUE TITLE
Option for clearing before build

### ISSUE THREAD

**Issue by regexident** [passcod/cargo-watch#28]
It would be nice to have an optional command-line option for clearing the console before building. 
So that on does not have to search for the beginning of the current output in the console.

**Comment by passcod** [comment]
Not going to implement that in cargo watch, but you can do it easily by creating a script called eg `cargo-clearscreen` that clears the screen, putting it in your path, and calling `cargo watch clearscreen build` etc.

**Comment by regexident** [comment]
Good point. Works flawlessly:

    #!/bin/bash
    printf '\e]50;ClearScrollback\a' # iTerm 2
    clear && printf '\e[3J' # Most other Terminals

**Comment by passcod** [comment]
This is now implemented! From Cargo Watch 3.2.0, use `--clear`.

**Comment by regexident** [comment]
> Not going to implement that in cargo watch …

… 

> This is now implemented! …

😈 _evil laughter_ 😏

…

👍
