### ISSUE TITLE
Tracking issue: trigger rerun on non-.rs-file changes

### ISSUE THREAD

**Issue by LukasKalbertodt** [passcod/cargo-watch#31]
Changes of files, whose names do not end with `.rs` are currently ignored. Sometimes other files are expected to trigger a rerun of compilation. Two examples:
- parser generators like `lalrpop` will generate `.rs` files from `.lalrpop` files that are in the source directory
- sometimes arbitrary files are included via `include_str!` or something similar

**Comment by passcod** [comment]
Less edge-casey example: the `Cargo.toml`! Surely if that changes it could affect the whole project…

**Comment by Nemo157** [comment]
If https://github.com/rust-lang/cargo/issues/1989 is implemented then that could take care of determining what files are important.

**Comment by passcod** [comment]
For my reference, the linked issue actually asks for a Cargo API that gives the list of paths that would trigger a recompile.

**Comment by passcod** [comment]
:+1: Going to do this. Don't have an ETA, but it's on the todolist.

**Comment by JelteF** [comment]
Being able to watch .md files would also be really useful for automatically generating the docs.

**Comment by passcod** [comment]
This is now done with the entirely new version 4.0.0!
