### ISSUE TITLE
Tracking issue: use regex! macros when they become stabilized

### ISSUE THREAD

**Issue by LukasKalbertodt** [passcod/cargo-watch#32]
This issue as a reminder, though we will probably have to wait for quite some time still.

**Comment by passcod** [comment]
Given the `regex!` macro is "orders of magnitude slower", to quote the crate documentation, let's not do this.

**Comment by LukasKalbertodt** [comment]
Makes sense. But I am really confused why they can't use the standard regex building algorithm in `regex!`... whatever.

Someone should remove [this comment](https://github.com/passcod/cargo-watch/blob/8606461c26fcde67b3e32c8c7959310d95382630/src/cargo.rs#L40-L41) now. And looking at it, maybe we should combine the `IGNORED_FILES` regexes into one regex?
