### ISSUE TITLE
Watch `examples` folder

### ISSUE THREAD

**Issue by LukasKalbertodt** [passcod/cargo-watch#33]
Currently changes in the examples folder are ignored. This is probably not intended.

**Comment by passcod** [comment]
This is indeed an oversight.

**Comment by fosskers** [comment]
Sorry to dig up such an old issue. Currently, `cargo watch` seems to detect a change in `examples/` (its output flashes in the terminal) and yet compilation errors from example code doesn't actually display. `rust-analyzer` seems to detect the error though, and I see red lines in my editor, at least.

Any idea what might be happening here?

**Comment by passcod** [comment]
Sure, cargo watch just runs `cargo check` by default and that doesn't compile examples (or tests) by default.

**Comment by fosskers** [comment]
Thanks! For anyone wandering in from the FuTuRe, here's what got it working for me:
```
cargo watch -c -q --exec="check --examples"
```
