### ISSUE TITLE
Watch custom lib and bin directories

### ISSUE THREAD

**Issue by yberreby** [passcod/cargo-watch#35]
Cargo [supports custom paths for library and binary targets](http://doc.crates.io/manifest.html#configuring-a-target), but `cargo-watch` does not read Cargo.toml to know what directories to watch.

That is, if I have `lib/lib.rs` and `bin/main.rs`, `cargo-watch` does not detect changes to these files.

**Comment by passcod** [comment]
Maybe duplicate/related to #31.

**Comment by yberreby** [comment]
Not quite a duplicate, but indeed related and waiting on rust-lang/cargo#1989. Maybe leave this issue open until the upstream issue is resolved.

**Comment by passcod** [comment]
👍 Going to do this. Don't have an ETA, but it's on the todolist.

Initial implementation will parse the Cargo.toml or something to watch the right thing.

**Comment by passcod** [comment]
This is now done with the entirely new version 4.0.0! It's a bit different from what was said here, as v4 watches the entire project and filters out `target/` (and whatever other patterns you specify) instead of only watching specific folders.
