### ISSUE TITLE
Should it run the command upon start up, before any files are modified?

### ISSUE THREAD

**Issue by rory** [passcod/cargo-watch#37]
Proposal: When cargo watch starts, run the command, even if no file has changed.

I've often started cargo watch when started working on a project, and it clearly doesn't do anything until a file has changed. Sometimes I can't remember if all the tests passed (or if the code compiles), and I'd like to see the output of cargo test. So I need to make a simple change to something so that it'll run and I can see. But if cargo watch ran the command as soon as it was started, this would be easier.

But maybe that's my workflow, does this sound useful to other people?

**Comment by passcod** [comment]
I'm of either mind on this, so I'll wait for community feedback too.

**Comment by aij** [comment]
Yes please.

**Comment by rory** [comment]
Suggestion: Use Github's new "Add a reaction" feature for voting. Add a +1 (:+1:) to this comment to say "I would like this feature" and -1 (:-1:) to say "I would not like this feature"

**Comment by passcod** [comment]
If you wish to, sure, but do add your use case if it is different from the top-post. I'd love to have more insight into why people would want one or the other.

**Comment by robinst** [comment]
Used `cargo watch run` with a simple [iron](http://ironframework.io/doc/iron/) example server, and expected it to run the command.

Maybe it should be an optional thing or depend on the cargo command?

**Comment by passcod** [comment]
I think I'm going to rebuild cargo watch to more in the model of remy's
`nodemon`, if you know of it, after I do Notify v3. This would include the
functionality requested in this ticket.

**Comment by shepmaster** [comment]
I'm all for this as I wanted to `watch` a server, so the first run before anything changes is definitely useful. One alternate thing is to allow pressing <kbd>Enter</kbd> to trigger a build, regardless of the state of files. I believe that [guard](https://github.com/guard/guard) allows something similar.

**Comment by passcod** [comment]
Nodemon does it by typing `rs` then Enter, which guards against restarting inadvertently if an interactive program is watched, or if one likes to use blank lines to visually separate runs when doing verbose debugging. That's probably what I'll go with. I use nodemon all the time, it's a very useful tool — it is very much the vision for cargo watch.

Speaking of, as much as I'd like to keep users here, I have no illusion of being able to bring it to greatness any time soon, so if you happen to have npm/node installed and want a very good cargo-watch alternative, go with nodemon:

```
# With long options for clarity:
$ nodemon --ext rs,toml --exec 'cargo run' --watch src --watch test --watch examples

# Short options for brevity:
$ nodemon -e rs,toml -x 'cargo run' -w src -w test -w examples
```

That should have the requisite behaviour.

**Comment by robinst** [comment]
For other people landing here, there's now also a nodemon-like tool written in Rust: https://github.com/mattgreen/watchexec/

    $ watchexec --run-initially --restart "cargo run"

**Comment by passcod** [comment]
Note that `--run-initally` is the default now, so you don't need to specify it.

**Comment by passcod** [comment]
This is now done with the entirely new version 4.0.0! It will run the command upon starting by default, but you can disable the behaviour using `--postpone`.
