### ISSUE TITLE
Also watch Cargo.toml

### ISSUE THREAD

**Issue by Yamakaky** [passcod/cargo-watch#39]

**Comment by passcod** [comment]
👍 Going to do this. Don't have an ETA, but it's on the todolist.

**Comment by passcod** [comment]
Tries to implement that real quick, but it depends on #31, so I'll go do that first.

**Comment by passcod** [comment]
This is now done with the entirely new version 4.0.0! See details in #31 and the readme.

**Comment by Yamakaky** [comment]
Yeay!
