### ISSUE TITLE
warning "unused import" in main.rs

### ISSUE THREAD

**Issue by benaryorg** [passcod/cargo-watch#41]
I just installed it on latest stable Rust and got this:

```
.cargo/registry/src/github.com-88ac128001ac3a9a/cargo-watch-3.1.0/src/main.rs:17:14: 17:19 warning: unused import, #[warn(unused_imports)] on by default
.cargo/registry/src/github.com-88ac128001ac3a9a/cargo-watch-3.1.0/src/main.rs:17 use notify::{Error, RecommendedWatcher, Watcher};
```

I am not sure if this is just on my platform or on others too, or if this would break anything, so I'm filing an issue rather than sending a PR.

**Comment by passcod** [comment]
Warnings, by definition, don't break anything. There are a number of warnings when building both cargo-watch and Notify (the primary dependency, which is also a project of mine). They'll get cleaned up eventually, in a future release. I don't have much time to work on these projects currently, so I tend to ignore harmless warnings, but anyone's welcome to PR fixes :)
