### ISSUE TITLE
Clean screen before run

### ISSUE THREAD

**Issue by samber** [passcod/cargo-watch#42]
Hi guys,

The rust compiler is very ...talkative.

It would be awesome to add a `--clean-screen` flag to `cargo watch`, to clear the screen before compiling and running the Rust program.

**Comment by passcod** [comment]
This depends on the terminal emulator used, doesn't have an effect if piped, and is notoriously hard to do reliably and correctly. But if someone wants to contribute...

**Comment by dwijnand** [comment]
I jimmied together an easy workaround/solution for myself:
https://twitter.com/dwijnand/status/828907442176143361

But I agree it would be nice if this were a built-in feature.

@passcod do you know of any prior art on doing it reliably and correctly?

**Comment by passcod** [comment]
Apparently someone did this last year: https://github.com/moretea/cargo-clear Same idea.

It seems Windows 10 can use ANSI escape sequences if enabled:
- https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling/1050078#1050078
- https://msdn.microsoft.com/en-us/library/windows/desktop/mt638032(v=vs.85).aspx

Can anyone test whether `cls` works in Unixy shells on Windows? If yes it could be one way to achieve this, by simply compiling `cls` on windows targets, and `clear` on others. A bit dodgy, but a simple partial solution at least.

**Comment by passcod** [comment]
Done in 3.2.0. Look at the Readme for more usage, but basically: `--clear`.
