### ISSUE TITLE
Request:  Watch anything

### ISSUE THREAD

**Issue by rosshadden** [passcod/cargo-watch#44]
One thing I like a lot about `nodemon` is you can use it with any project (by passing it a command option, obviously).  `cargo-watch` accepts arbitrary commands, but throws an error when you try to use it in a non-rust project.

**Comment by passcod** [comment]
:+1:

**Comment by robinst** [comment]
@rosshadden: Take a look at [watchexec](https://github.com/mattgreen/watchexec/)!

**Comment by passcod** [comment]
Yeah, closing this because that's what watchexec does. I'm restricting focus such that cargo-watch is a tool for cargo-based development, and watchexec is a general run-command-when-files-change tool.
