### ISSUE TITLE
Dupplicated build with vim

### ISSUE THREAD

**Issue by Yamakaky** [passcod/cargo-watch#47]
Sometimes, instead of sunning the build command one time, `wargo-watch` run it multiple times. I can't really find why, except that sometime `touch src/lib.rs` builds one time and `vim src/lib.rs` builds two. Maybe it's something like vim that  saves then touch or something like that, or a race condition in the scheduler loop.

**Comment by passcod** [comment]
This has to do with debouncing events on the notify side, and is tracked at https://github.com/passcod/rsnotify/issues/63 which should be released soon.

**Comment by Quantumplation** [comment]
:D I noticed that passcod/notify#63 got released.  Any chance it will make it here soon?

**Comment by Yamakaky** [comment]
For the record, I now use `watchexec` which is more general and doesn't have this problem.

**Comment by passcod** [comment]
This should be fixed now.

**Comment by Yamakaky** [comment]
Cool!
