### ISSUE TITLE
"Bad file descriptor" error on windows 10 bash subsystem

### ISSUE THREAD

**Issue by Tzrlk** [passcod/cargo-watch#49]
Running `cargo watch` on the ubuntu bash subsystem of windows 10 results in the following error:

```shell
> cargo watch
ERROR:cargo_watch: Failed to init notify (Io(Error { repr: Os { code: 9, message: "Bad file descriptor" } }))
```

Does this mean anything to you?

**Comment by passcod** [comment]
Cargo Watch should now fallback to polling if it can't use the native version. I'm thinking this is an issue of Windows Bash reporting as Linux for the rust build system, and Notify assuming that inotify is available. If it doesn't fallback, try to force it with `--poll`.

**Comment by passcod** [comment]
Closing. Reopen if it still occurs.

**Comment by passcod** [comment]
I believe inotify supported landed in the latest release of the Linux subsystem, so this should be properly fixed now.
