### ISSUE TITLE
Cargo watch never triggers on OS X El Capitan

### ISSUE THREAD

**Issue by paulkernfeld** [passcod/cargo-watch#54]
I'm new to Rust, so I'm probably doing something stupid. I installed by running `cargo install cargo-watch`.

When I run `cargo watch` and edit a file, tests don't seem to run. It just says `Waiting for changes... Hit Ctrl-C to stop.` and nothing seems to happen after that.

```
paul ~/projects/iron master $ ls src/ && cargo watch &
main.rs
[1]+ running: cargo watch & & (2635)
paul ~/projects/iron master $ echo "" >> src/main.rs
paul ~/projects/iron master $ fg
[1]+ running: cargo watch & (2635)
Waiting for changes... Hit Ctrl-C to stop.
^C
```

**Comment by passcod** [comment]
What platform?

**Comment by paulkernfeld** [comment]
This is on OSX (El Capitan?). Right now I'm at work, but I can provide better details when I get home. What details can I provide besides the version of `rustc`?

**Comment by paulkernfeld** [comment]
My version of `rustc` is `rustc 1.17.0-nightly (6eb9960d3 2017-03-19)`, and my version of `cargo-watch` is `3.1.2`, if that helps.

**Comment by passcod** [comment]
Can you try now? I don't think it would fix anything, but I've updated the dependencies, just in case.

**Comment by passcod** [comment]
Try to use the `--poll` option introduced in 3.2.0, see if that helps.

**Comment by ereichert** [comment]
It appears I'm suffering from the same problem. 

I just upgraded to 3.2.0 and I've tried cargo watch with and without the --poll option and I cannot get the watch to trigger. 

I'm also on El Capitan running rustc 1.17.0-nightly (485358400 2017-03-18).

**Comment by passcod** [comment]
Okay, this is obviously bad — but I can't debug this effectively as I don't have a mac on hand. I'll try to figure something, but it may have be come after I finish Cargo v4.

In the meantime, could you try running with the `RUST_LOG=*` envvar and gist the logs?

**Comment by passcod** [comment]
Testing on Sierra, `touch src/afile.rs` doesn't trigger, but editing in vim or atom does, even if it's just saving the file right after opening it, without modifications. With `--poll`, `touch src/afile.rs` works. It does take one second to trigger after the file modification (in all cases) because of the debouncing delay.

I can't test on El Capitan, sorry.

**Comment by ereichert** [comment]
I'll do more testing at some point today and follow your instructions.

**Comment by ereichert** [comment]
Tested without --poll and with --poll and debug turned on for both.

Same result.

==> RUST_LOG=debug cargo watch test 
Waiting for changes... Hit Ctrl-C to stop.
DEBUG:cargo_watch::schedule: path changed: /Users/ereichert/dev/counter/src/main.rs___jb_old___
INFO:cargo_watch::schedule: Ignoring change on 'main.rs___jb_old___' (/Users/ereichert/dev/counter/src/main.rs___jb_old___)
DEBUG:cargo_watch::schedule: path changed: /Users/ereichert/dev/counter/src/main.rs___jb_old___
INFO:cargo_watch::schedule: Ignoring change on 'main.rs___jb_old___' (/Users/ereichert/dev/counter/src/main.rs___jb_old___)
DEBUG:cargo_watch::schedule: path changed: /Users/ereichert/dev/counter/src/file_handling.rs___jb_old___
INFO:cargo_watch::schedule: Ignoring change on 'file_handling.rs___jb_old___' (/Users/ereichert/dev/counter/src/file_handling.rs___jb_old___)

==> RUST_LOG=debug cargo watch "--poll test"
Waiting for changes... Hit Ctrl-C to stop.
DEBUG:cargo_watch::schedule: path changed: /Users/ereichert/dev/counter/src/main.rs___jb_old___
INFO:cargo_watch::schedule: Ignoring change on 'main.rs___jb_old___' (/Users/ereichert/dev/counter/src/main.rs___jb_old___)
DEBUG:cargo_watch::schedule: path changed: /Users/ereichert/dev/counter/src/file_handling.rs___jb_old___
INFO:cargo_watch::schedule: Ignoring change on 'file_handling.rs___jb_old___' (/Users/ereichert/dev/counter/src/file_handling.rs___jb_old___)
DEBUG:cargo_watch::schedule: path changed: /Users/ereichert/dev/counter/src/file_handling.rs___jb_old___
INFO:cargo_watch::schedule: Ignoring change on 'file_handling.rs___jb_old___' (/Users/ereichert/dev/counter/src/file_handling.rs___jb_old___)

**Comment by passcod** [comment]
Ok, so it _is_ receiving events, but only on `.rs___jb_old___` files, and then rightfully ignoring those.

Do you have other files in there? Are they changing? For that matter, that extension looks weird, do these files actually exist at those filenames?

**Comment by ereichert** [comment]
Multiple files. 

==> ls -A1 src/
file_handling.rs
lib.rs
main.rs
record_handling.rs

I've tried changing a few of them all with the same result.

**Comment by passcod** [comment]
Right, so I guess what's happening is _something_ is appending `___jb_old___` to the filename reported through notify. I'll investigate.

**Comment by passcod** [comment]
Ah, these are IntelliJ files, apparently. If you create a e.g. `notifytest.rs` file in the folder with the command line, does it trigger?

**Comment by ereichert** [comment]
I was just typing as you posted. It's coming from Intellij Idea.

**Comment by ereichert** [comment]
Using vim, I created the notifytest.rs and can see the .swp file being ignored. On save the tests run.

It seems, at least on my rig, it's a problem of ignoring the final saves???

**Comment by ereichert** [comment]
http://stackoverflow.com/questions/23271895/temporary-jb-old-file-in-phpstorm-and-webstorm-causing-errors

Turning safe write off fixes the problem.

**Comment by passcod** [comment]
Or the "final saves" not being saves at all (but renames/moves, which get reported and tracked differently). If you just `echo foo > test.rs`, i.e. a straight write, it should trigger, right?

**Comment by passcod** [comment]
Yeah, I suspected that, but it's a bit annoying to have to turn that off.

**Comment by ereichert** [comment]
Yes, it is. But at least we know the cause.

@paulkernfeld Are you using Intellij or something else? And does it create temp files?

**Comment by ereichert** [comment]
Didn't mean to step on your toes there. Day job habit.

**Comment by passcod** [comment]
No problem :)

**Comment by paulkernfeld** [comment]
I did originally notice this while using Intellij. I thought that it also happened when modifying the files from my shell. I will run the same tests as @ereichert ran above when I have some free time.

**Comment by paulkernfeld** [comment]
Slight correction: I am actually using Sierra on this computer, not El Capitan.

After upgrading to `cargo-watch 4.0.0`, both Intellij and appending seem to work fine! So, from my perspective, everything seems to be resolved.

Is there anything else that I should test?

**Comment by passcod** [comment]
Nope, that's all good :) v4 does include some improvements that affect this issue, so we'll call it solved.
