### ISSUE TITLE
Broken in Windows 10 cmd

### ISSUE THREAD

**Issue by nepp2** [passcod/cargo-watch#59]
If I run `cargo watch` from Git Bash in Windows 10, it runs successfully. It does seem to run more often than should be necessary, but perhaps that is the fault of my editor (VS Code).

If I run `cargo watch` from cmd in Windows 10, I see:

```
ERROR:cargo_watch::schedule: Couldn't start, waiting for file change
ERROR:cargo_watch::schedule: The system cannot find the file specified. (os error 2)
```

I get this message quite a few times, and never see any useful output. `cargo build` runs fine.

For now I will continue using Git Bash, but for some reason it does not support the syntax colouring in rustc's output, unlike cmd. Syntax colouring is also broken when I run `cargo build`, so that's not an issue introduced by cargo-watch.

**Comment by passcod** [comment]
Can you give a log with `RUST_LOG=cargo_watch=debug`?

**Comment by Measter** [comment]
It seems I have the same issue. Here's the log:

```
PS D:\Programming\Rust\Rust Projects\test_project> cargo watch
INFO:cargo_watch: Delay: 1 seconds
INFO:cargo_watch: Watches: ["D:\\Programming\\Rust\\Rust Projects\\test_project\\"]
INFO:cargo_watch: Commands: [Cargo("check")]
DEBUG:cargo_watch: Getting current working dir
DEBUG:cargo_watch: Enabling filter from gitignores
INFO:cargo_watch: Filters: ["/target/**"]
INFO:cargo_watch::filter: Walking tree for gitignores
INFO:cargo_watch::filter: Parsing gitignore: D:\Programming\Rust\Rust Projects\test_project\.gitignore
INFO:cargo_watch::filter: Adding extra pattern: /target/**
INFO:cargo_watch::filter: Built filter with 2 patterns
INFO:cargo_watch: Settings: []
[Watching for changes... Ctrl-C to stop]
INFO:cargo_watch::schedule: Starting job: Expression(Then(Expression(Io(Unchecked, Expression(Then(Expression(Cmd(["echo", "[Running \'cargo check\']"])), Expression(Sh("cargo check")))))), Expression(Cmd(["echo", "[Finished running]"]))))
ERROR:cargo_watch::schedule: Couldn't start, waiting for file change
ERROR:cargo_watch::schedule: The system cannot find the file specified. (os error 2)
INFO:cargo_watch::schedule: Starting main loop
```

I believe the problem is how you try to echo. The issue here, I think, is that on Windows "echo" is not a program, but a command build into the shell. To make that work, I think you would need to do something like this:

`cmd!("cmd", "/C", "echo [Finished running]")`

**Comment by passcod** [comment]
Ah, right. Well, that's easy enough to fix.
