### ISSUE TITLE
Should cargo-watch trigger when I run "git status?"

### ISSUE THREAD

**Issue by paulkernfeld** [passcod/cargo-watch#60]
Right now, running `git status` triggers cargo-watch for me. This is by no means a serious problem for my use case, but I wonder if this might cause issues for others.

**Comment by passcod** [comment]
`git status` shouldn't _write_ anything, unless you have a git plugin or it hits a `git gc` run… so that's a bit strange. Nevertheless, watching the `.git` folder, which I suspect is the issue here, should have been prevented. Fixed in 4.0.3.

**Comment by paulkernfeld** [comment]
Awesome, thanks!
