### ISSUE TITLE
Ignore .git/

### ISSUE THREAD

**Issue by Yamakaky** [passcod/cargo-watch#64]
`touch .git/p` launches a build.

**Comment by passcod** [comment]
Platform, debug logs, etc? Windows glob matching is iffy right now, but Unixes should have that fixed since 4.0.3.

**Comment by Yamakaky** [comment]
Oh, I use https://aur.archlinux.org/packages/cargo-watch/, which is 4.0.1. I'll try again when it's updated.

**Comment by Yamakaky** [comment]
Yeah it's good, sorry.
