### ISSUE TITLE
Single-command install / depend on watchexec automatically

### ISSUE THREAD

**Issue by passcod** [passcod/cargo-watch#65]
To make v5 installable properly using the normal `cargo install cargo-watch`, we probably need to figure out how to either:

- embed watchexec (preferred, as it will make sure we don't break if watchexec's interface changes)
- install watchexec as a dependency

**Comment by mattgreen** [comment]
This is an exciting development. If there's any way I can help please let me know.

**Comment by passcod** [comment]
This is now ready to release as soon as we watchexec's next release get onto crates.io :)

**Comment by mattgreen** [comment]
This is up on crates.io now as 1.8.1.

One caveat: because `watchexec` is an app first and foremost, it will be hard to continue to evolve and guarantee I won't break semver via changes to to `Args`. Thus, in your shoes, I'd pin it to an exact version and bump it only as necessary. (I'm not looking to break the `Args` struct anytime soon, mind you.)

**Comment by passcod** [comment]
No problem :) I'll tighten the version specifier, the advantage of this
method of embed is also that I *can* bind to versions tightly.

**Comment by passcod** [comment]
Done in [5.0.0](https://github.com/passcod/cargo-watch/releases/tag/v5.0.0).

**Comment by mattgreen** [comment]
Note: you'll want to bump to watchexec 1.8.3 to avoid a dumb bug relating to file changes being triggered in `.git` dirs that 1.8.1 had.

**Comment by passcod** [comment]
Ah, that's not really an issue given I build my own Args — [I'd already added .git ignoring](https://github.com/passcod/cargo-watch/commit/7f1eeb712197f40ab2fe40780b952c242283d187) — but ooops, I just noticed a bug/typo with that commit, so I'll fix that.

(Also, you can avoid repetition by using `format!("*{s}.git{s}*", s=MAIN_SEPARATOR)`
