### ISSUE TITLE
Path dependency on watchexec

### ISSUE THREAD

**Issue by ishitatsuyuki** [passcod/cargo-watch#66]
Make sure you didn't forget to remove the development hack:

https://github.com/passcod/cargo-watch/blob/871245b8bca36886958144ada2873f4cc1ac2675/Cargo.toml#L16

**Comment by passcod** [comment]
Thank you, that was known. (And will be done soon.)

**Comment by passcod** [comment]
Version [5.0.0](https://github.com/passcod/cargo-watch/releases/tag/v5.0.0) was released properly.
