### ISSUE TITLE
Add support for ~/.gitignore

### ISSUE THREAD

**Issue by behnam** [passcod/cargo-watch#67]
When respecting `gitignore` files to not watch, the current implementation only looks at the local `.gitignore` file, but not other ones that `git` itself recognizes, specially `~/.gitignore`.

The best and common practice to gitignore editor temp files is to put the patters in `~/.gitignore`, as they are something user-dependent and not project-dependent (and its hard for projects to stay inclusive to all types of editors and their settings).

Because of this, right now, when using `cargo watch`, I get a new execution whenever I open/close my editors (VIM), which is very often, because of the `.*.swp` files being created and dropped.

**Comment by passcod** [comment]
This is an issue with our upstream [watchexec](https://github.com/mattgreen/watchexec), not with cargo-watch.
