### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by bpglaser** [passcod/cargo-watch#71]
Version 5.0.3 fails to run on Windows 10. Can confirm that cargo-watch works with version 5.0.1

> C:\Users\Brad\Development\seam-carving-resize>rustup show
> Default host: i686-pc-windows-gnu
> 
> stable-i686-pc-windows-gnu (default)
> rustc 1.17.0 (56124baa9 2017-04-24)

> C:\Users\Brad\Development\seam-carving-resize>cargo watch --version
> cargo-watch 5.0.3

> C:\Users\Brad\Development\seam-carving-resize>cargo watch
> The filename, directory name, or volume label syntax is incorrect.

cargo watch --debug
output: https://gist.github.com/bpglaser/8f08b9546d7a541109bb52bad4d9abdc

**Comment by passcod** [comment]
Hmm, I think I know a better fix for #70, which would solve this. I'll try tomorrow (bedtime now).

**Comment by passcod** [comment]
Probably fixed with 5.0.4. Can you check?

**Comment by hcpl** [comment]
Ah, my bad. Should have tested more thoroughly.
And 5.0.4 works for me (Windows 10 version 1511).

**Comment by passcod** [comment]
Great! :)
