### ISSUE TITLE
Wait for the commands to finish

### ISSUE THREAD

**Issue by vorner** [passcod/cargo-watch#73]
Currently, if I let `cargo watch` execute some long-running command and I save a file again while the command is still running, the command gets killed and is run again.

I'd like an option that would change the behaviour and let the command finish before starting it again. If something was changed while the command was still running (possibly multiple times), it would start it after the previous run completed.

My use case is something like this. I start `cargo watch -x doc`, open relevant part of documentation in the browser and start editing the documentation comments in the source files. If I save only from time to time, the documentation is rebuilt on each save, the browser reloads the documentation and I can keep an eye on how it looks like and fix any formatting issues, etc. However, if I save too often (which I'm used to), the command never finishes and I get no updates of the documentation in the browser. In my opinion, having less often updates is better than having none at all.

I have similar problem with other scenarios, like running `cargo watch -x test --all` ‒ it keeps compiling and compiling and never gets to actually run the tests.

**Comment by passcod** [comment]
If you can figure out a watchexec command/options that do that, I can add a flag here that would set those.

**Comment by vorner** [comment]
I believe the needed flag is *not* setting restart. This does what I want (well, with a bit different command and limited to only some files to be watched, but it doesn't kill and restart the command):

```
watchexec -e md -w doc/ make doc
```

I think setting this to `false` would solve my problem: https://github.com/passcod/cargo-watch/blob/master/src/main.rs#L146

**Comment by passcod** [comment]
Done in 5.1.0.

**Comment by vorner** [comment]
Thank you, this was super fast :-).
