### ISSUE TITLE
Allow running outside of cargo project

### ISSUE THREAD

**Issue by bjorn3** [passcod/cargo-watch#74]
I currently need to use commands like

```sh
cd src && cargo watch -s "cd ../no_llvm_build && ../x.py test --stage 0"
```

when using `cargo watch` with rustc.

**Comment by passcod** [comment]
That is [explicitly an anti-goal](https://github.com/passcod/cargo-watch#i-want-to-run-cargo-watch-outside-of-a-cargo-project), but I suppose a rustc project _could_ be in scope... can you give more details?

**Comment by bjorn3** [comment]
Its rustc itself. It contains a src directory which is a cargo workspace if im correct.

I will try watchexec.

**Comment by passcod** [comment]
Ah well, given rustc requires to use its own build script, using cargo-watch the way you were _is_ the right way. How would it know what to run otherwise?

**Comment by bjorn3** [comment]
I meant not having to `cd ../no_llvm_build` inside the -s arg.

**Comment by passcod** [comment]
Right, but cargo-watch then wouldn't know where to run from, given there would be no Cargo.toml in the current dir nor parents. It's just not suited to do that.

**Comment by bjorn3** [comment]
Okay
