### ISSUE TITLE
Change how glob patterns apply (relative/absolute/relative to what) for better intuitiveness

### ISSUE THREAD

**Issue by paulkernfeld** [passcod/cargo-watch#79]
I love `cargo-watch`, and use it on everything! Right now, I am having a bit of trouble figuring out how to ignore a file properly.

The following invocations successfully ignore `README.md`:
* `cargo watch -w src -s "touch README.md"`
* `cargo watch -i '.md' -s "touch README.md"`
* `cargo watch -i '*.md' -s "touch README.md"`

The following invocations don't ignore `README.md`, which means that `cargo watch` loops forever:
* `cargo watch -i 'README?md' -s "touch README.md"`
* `cargo watch -i 'README*' -s "touch README.md"`

This doesn't correspond to my intuition about how globbing should work. I would find it very helpful to have some more docs, or a link to docs, to help me understand how to use the globbing correctly.

**Comment by passcod** [comment]
I believe this uses glob: https://doc.rust-lang.org/glob/glob/index.html although documentation over there seems sparse? If you find more docs (or end up writing some) I'd gladly link them in the readme.

**Comment by Boscop** [comment]
Why doesn't it ignore `app.db` even though I have it in .gitignore AND I pass it to the command like:
`cargo watch -i app.db -x "run -p mybin"`
(I'm running this in a workspace where mybin is the binary I want to run.)

My .gitignore looks like this:
```
target
.env
app.db
```

**Comment by paulkernfeld** [comment]
I found some [useful docs for `glob::Pattern`](https://doc.rust-lang.org/glob/glob/struct.Pattern.html), however that does not explain this particular issue, so I'll keep digging.

**Comment by paulkernfeld** [comment]
Hmm, it looks like globs added with `-i` are not prepended with `*/`. If I do `-i */README.md`, then `README.md` is successfully ignored.

```
*** built glob set; 0 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 3 regexes
*** Loaded "/Users/paul/projects/test-cargo-watch/.gitignore"
*** Adding ignore: "*/.DS_Store"
*** Adding ignore: "*.swp"
*** Adding ignore: "*/.hg/**"
*** Adding ignore: "*/.git/**"
*** Adding ignore: "*/.svn/**"
*** Adding ignore: "*/target/**"
*** Adding ignore: "README.md"
```

**Comment by paulkernfeld** [comment]
Hmm, it looks like specifying the absolute path of `README.md` successfully ignores it. I think that the current behavior is a bit confusing; I had expected that `-i README.md` would ignore the file `README.md` in the project's root directory. Would you be okay with changing it so that `-i` ignores files using relative rather than absolute paths?

**Comment by passcod** [comment]
Hmm, yes, that sounds reasonable

**Comment by pascalw** [comment]
I'm running into this as well.

For example in my `.gitignore` I have:

```
/dist
```

But changes in the `dist/` directory still cause a reload. Practically this means that the `.gitignore` option is useless. The only way I can make the `dist/` directory ignored is by passing ` -i '*/dist/**'` which indeed is unintuitive.

**Comment by JeanMertz** [comment]
I ran into this as well. It's confusing, especially since the `--help` documentation states:

> your .gitignore files are used to filter paths.

Note that Cargo also ran into this confusion, and they switched from the `glob` crate to the [`ignore`](https://crates.io/crates/ignore) crate for exactly the same reason.

Might be worth doing the same for this project?

**Comment by passcod** [comment]
Closing in favour of upstream issue: https://github.com/watchexec/watchexec/issues/188.
