### ISSUE TITLE
Multiple commands broken in Powershell

### ISSUE THREAD

**Issue by Michael-F-Bryan** [passcod/cargo-watch#80]
At work I do my programming on a Windows 10 machine and have `cargo watch` running in the background to recompile everything, generate docs, and run the test suite. If you pass multiple `--exec` commands the last one always fails with a message like:

```
$ cargo watch --exec test --exec doc
[Running 'cargo test
error: no such subcommand: `doc']`

        Did you mean `doc`?
```

It looks like `cargo watch` injects a trailing `'` or some other character which breaks the command. I've attached the output when passing in the `--debug` flag. 
[output.txt](https://github.com/passcod/cargo-watch/files/1350865/output.txt)

---

Just out of curiosity, why do you use the local shell instead of executing the commands as a subprocess (using `std::process::Command`) directly? Wouldn't that give more consistent behaviour?

**Comment by Michael-F-Bryan** [comment]
I think I've figured out the problem. It's because you've joined all commands to be run using `&&`, and windows handles that differently to bash (operator precedence and quoting). 

If I run the command directly I see this:

```
$ cmd.exe /C "echo [Running \'cargo test && cargo doc \'] && cargo test"
[Running \'cargo test
error: Invalid arguments.

Usage:
    cargo doc [options]
```

It looks like `cmd.exe` actually interprets this "and"-ing the following three commands together,

- `echo [Running \'cargo test`
- `cargo doc \']`
- `cargo test`

**Comment by passcod** [comment]
That's a known issue, use `-q` to disable the "Running..." message and thus workaround the problem.

Windows support is iffy at the moment. Unfortunately I have neither the machine, the will, nor the time to fix it at the moment. Pull requests would be very welcome.

----

On the contrary, no, it woudn't. Using the shell makes sure that subjobs are also contained, while invoking subprocesses wouldn't. Watchexec does the heavy lifting there, and does a great job of covering the dozens of edge cases and various concerns that stem from running user-provided commands; cargo watch used to do that itself but it was always more or less terrible at it.

**Comment by Michael-F-Bryan** [comment]
> That's a known issue, use -q to disable the "Running..." message and thus workaround the problem.

That's good enough for me. I mainly do Rust at home where I'm using Arch Linux, so this isn't a massive issue.

> Using the shell makes sure that subjobs are also contained, while invoking subprocesses wouldn't

Good point. It'd be annoying if the subcommand failing was able to bubble up and kill the `cargo watch` process.  The best solution might be if you could pass multiple commands to `watchexec`, but that judging from how they want to keep everything as uncomplicated as possible that may not be something they want to add. 

I'll create an issue on the watchexec repo and see what they say. Depending on how it goes I may end up sending a PR to fix this.

**Comment by passcod** [comment]
Good idea! Thanks for doing that

**Comment by mattgreen** [comment]
I got this to work:

    > cmd.exe /C "echo [Running \"cargo test ^&^& cargo doc \"] && cargo test"

Note the `^` character for escaping the ampersands there.

**Comment by Michael-F-Bryan** [comment]
It [looks] like it wouldn't be *too* difficult to add in a check which gives the correct `&&` for a given platform.

You'd want the hard-coded `" && "` to instead defer to some `echo_cmd_separator()` function which does conditional compilation to deal with the differences between unix shells and `cmd.exe`.

```rust
if !matches.is_present("quiet") {
        let start = {
            format!("echo [Running '{}']", commands.join(" && "))
        };

        commands.insert(0, start);
        commands.push("echo [Finished running]".into());
    }
```

But is there any guarantee that the shell being used in Windows is always going to be `cmd.exe` compared to something else like Powershell or the "Windows Subsystem for Linux"? 

[looks]: https://github.com/passcod/cargo-watch/blob/4810b533292873be68fb6396765481dbf14e5d45/src/main.rs#L53

**Comment by passcod** [comment]
The multiple-shells-behaving-differently problem on Windows is probably the biggest one I have when implementing things right now. I'm tempted to replace the `&&` with english, writing something like `Running "cargo test" then "cargo doc"` and doing some sanitising (because what if you pass `-s "foo && bar"`?).

**Comment by Michael-F-Bryan** [comment]
> I'm tempted to replace the `&&` with english, writing something like `Running "cargo test" then "cargo doc"` and doing some sanitising (because what if you pass `-s "foo && bar"`?).

It may be worth breaking the list of commands out into its own type. This would just be a wrapper around a `Vec<String>`, but let you do validation whenever pushing a new command. You could emit a warning on the `push()` method if it *looks* like the user is passing in a command like `-s "foo && bar"` when they really wanted `-s "foo" -s "bar"`, using the `--quiet` option to tell it to be quiet if that's what you really intended.

... Or is that over-complicating things?

**Comment by mattgreen** [comment]
Right now `cmd.exe` is [hardcoded](https://github.com/mattgreen/watchexec/blob/8770ae39679a7cb1c858659a88d95da6880a34f6/src/process.rs#L201) in watchexec. I am OK with committing to keeping that and making it a breaking change if I move away from it for some reason.

This might be wrong under Windows Subsystem for Linux. But if users have that, I really would prefer if users would download a Linux version and use that. Which leaves PowerShell. TBH, I have no idea how well it works under that.

**Comment by passcod** [comment]
@Michael-F-Bryan A bit overcomplicating, I think, especially as there's instances you really do want to use `&&` literally, e.g. when doing more advanced control flow like `foo && bar || qux` and using subshells `foo $(bar && baz)`. The command string being passed relatively unchanged also makes it very easy to reason about what the command does, and that advantage would diminish if we do more processing.

**Comment by passcod** [comment]
@mattgreen Good to know. I'll go with conditional compilation, then.

**Comment by passcod** [comment]
I think this might be fixed
