### ISSUE TITLE
cargo watch -w doesn't exclude other files

### ISSUE THREAD

**Issue by Boscop** [passcod/cargo-watch#81]
I'm trying to have my exe only restart when it compiles, so I'm doing this in 2 instances of cmd.exe:
```
cargo watch -q -x check -s "echo > .watch"
cargo watch --no-gitignore -w .watch -x "run -p mybin"
```
I'm running this in a workspace where mybin is the binary I want to run and I have `.watch` in my .gitignore file.
But the 2nd command restarts mybin even when a rust source file changes on disk, not just when the `.watch` file changes, why?
Even when I don't run the 1st command, only the 2nd one, it also behaves that way...
Any help would be greatly appreciated :)

**Comment by passcod** [comment]
This is on windows?

I'm not sure why that doesn't work. Looks right to me.

Can you try with a file that _doesn't_ start with a dot, just to see?

**Comment by Boscop** [comment]
I tried with `_watch`, (also added it to .gitignore) but still the same behavior :(

**Comment by Boscop** [comment]
Considering https://github.com/passcod/cargo-watch/issues/82 too, it looks like ignoring files doesn't seem to work at all for me for some reason..

**Comment by passcod** [comment]
Closing (reopen if still occurs)
