### ISSUE TITLE
Does not stop at CTRL+C in "git for windows"’s bash shell

### ISSUE THREAD

**Issue by SimonSapin** [passcod/cargo-watch#86]
http://gitforwindows.org/ comes with a MYSYS64 terminal and a bash shell. When I use `cargo watch` in that environment, CTRL+C does nothing and the only way I have to stop it is closing the window. CTRL+C does work with other commands such as `cat`. It does work with `cargo watch` in PowerShell.

This might not be a bug in `cargo watch`, but do you have any idea what could cause it?

**Comment by passcod** [comment]
Likely an upstream bug. Check with watchexec?

**Comment by passcod** [comment]
Closing in favour of upstream issue: https://github.com/watchexec/watchexec/issues/184.
