### ISSUE TITLE
Only restart exe when new version builds successfully?

### ISSUE THREAD

**Issue by Boscop** [passcod/cargo-watch#88]
It would be very useful to have a command like `cargo watch -x run` but instead of killing the exe upon source change, and then not having an exe running when the build fails, it should always keep the latest version of the exe running which builds successfully (kind of like bors philosophy).
So it could be done by not doing `cargo run` but specifically invoking the exe file that is only overwritten on successful build, and watching only that file.
What do you think?

**Comment by passcod** [comment]
There's a way to do this in the readme: https://github.com/passcod/cargo-watch#restarting-an-application-only-if-the-buildcheck-succeeds

**Comment by passcod** [comment]
I think for now a `--only-if-succeed='cargo build'` option or similar is out-of-scope, because of how we're mostly a wrapper over `watchexec`. I'd link to another tool that does this smoothly, though!

**Comment by Boscop** [comment]
Ah right, sorry I forgot about that..
I actually tried that before but ran into this issue:
https://github.com/passcod/cargo-watch/issues/81
Which is still not working for me..

**Comment by Boscop** [comment]
I'm doing this now:

> cargo watch -q -x check -s "echo > .watch"

and 
>cargo watch --no-gitignore -w .watch -x run

But when I save a source file, it kills my exe, even though I have `.watch` in `.gitignore`, why?

**Comment by passcod** [comment]
Yeah, I'm still not able to reproduce on the Windowses I have access to.

There's another way to do this, which is to use `watchexec` directly or another watcher and touch/watch a file _outside_ the project (so you don't need to ignore anything), then use e.g. `cd ../projectname; cargo run`.

It's not awesome, but as a workaround...
