### ISSUE TITLE
Exclusive access to target dir collides with `cargo check`. Please don't try to lock the target dir immediately when file changes

### ISSUE THREAD

**Issue by Boscop** [passcod/cargo-watch#91]
My usual workflow is to use sublime where I do `cargo check` and it shows inline errors when the build fails, while having a console open with `cargo watch -x run`. 
But both try to get exclusive access to the `target` dir as soon as I save a file. Often `cargo watch` gets the lock first when I press Ctrl-B in Sublime (which saves the file and then does `cargo check`), and then I have to wait until **BOTH** builds have failed until I get the inline error messages in Sublime.
So I would really appreciate it if `cargo watch` could wait like 100ms to let `cargo check` go first :)

**Comment by passcod** [comment]
The lock is a cargo thing, so perhaps this could be something to raise with them as well.

Waiting before running could be done two ways:
- As a `sleep 0.1`, or
- As an option.

The sleep way requires positioned flag parsing, which wasn't possible with Clap when I built cargo watch. It might be possible now, but I don't think so. In that case, that's a feature that needs to be requested of Clap.

The option way needs to be done and exposed on Watchexec first before it can be used and exposed here.

**Comment by Boscop** [comment]
Btw, clap supports positional args now..

**Comment by Boscop** [comment]
Btw, clap supports positional args now..

**Comment by passcod** [comment]
No, no, I mean positional _flags_. As in, we need to be able to tell where each `-x` and `-s` flag was given absolutely, not the order within one kind as it is now.

Currently, this line:

```
cargo watch -s baz -x foo -s bar
```

is interpreted to mean:

```
cargo watch -x foo -s baz -s bar
```

because Clap only provides order within kind, so we know that `-s baz` comes before `-s bar`, but not that `-s baz` came before `-x foo`.

**Comment by passcod** [comment]
Also, as a hacky workaround, you can plop this in your path named, e.g. `cargo-sleep`:

```bash
#!/bin/sh
sleep $1
```

And then use: `cargo watch -x "sleep 0.1" -x check`...

**Comment by Boscop** [comment]
I'm on windows though..
I tried [this](https://stackoverflow.com/a/1672349):
```
> cargo watch -x "ping 127.0.0.1 -n 2 > nul" -x run
error: no such subcommand: `run']`

        Did you mean `run`?

> cargo watch -q -x "ping 127.0.0.1 -n 2 > nul" -x run
error: no such subcommand: `ping`

        Did you mean `init`?
```
Why doesn't it work?

**Comment by passcod** [comment]
`-x` is for cargo subcommands. `-s` will run arbitrary shell commands. See the readme for more details.

**Comment by Boscop** [comment]
Ah, I see. Ok, I created the file `"C:\Users\me\.cargo\bin\cargo-sleep.bat"` with this content:
```bat
ping 127.0.0.1 -n 2 > nul
```

But it's still not working, any idea why? :/
```
> cargo watch -x sleep -x run                   
[Running 'cargo sleep                           
error: no such subcommand: `run']`              
                                                
        Did you mean `run`?                     
                                                
                                              

> cargo watch -x sleep                          
[Running 'cargo sleep']                         
error: no such subcommand: `sleep`              
                                                
        Did you mean `clean`?                   
                                                
                                              

> cargo sleep                                   
error: no such subcommand: `sleep`              
                                                
        Did you mean `clean`?                   
                                                
```

Shouldn't `.bat` files work like any exe on windows?

**Comment by passcod** [comment]
At this point that's a cargo question. I'm not sure of what cargo does internally to pick those up or not.
