### ISSUE TITLE
Optionally pipe output to pager

### ISSUE THREAD

**Issue by casey** [passcod/cargo-watch#92]
It would be nice to have the option to pipe `cargo-watch` output to a pager, like `less` or `more`,  to avoid scrolling past the first lines of output if they overflow the screen.

**Comment by passcod** [comment]
Probably a [watchexec](https://github.com/mattgreen/watchexec) feature request.

**Comment by casey** [comment]
Thanks for the response! I just opened an issue on watchexec.

**Comment by passcod** [comment]
You can now kinda do this by piping to less within `-s`:

   cargo watch -s 'cargo check | less'`

(This is possible since 7.0.9.)

**Comment by casey** [comment]
Sweet, that's awesome. This works for me, so I'll close this issue.

**Comment by Matthias-Fauconneau** [comment]
Thanks for the tool. 
I was wondering how I'd achieve the restart with inotify_wait but this is much better.
Not sure how to make it more discoverable.

With colors and bat:
```shell
cargo watch -s 'cargo check --color always 2>&1 | bat -p --paging always'
```

**Comment by casey** [comment]
@Matthias-Fauconneau Just came back to this issue and saw your snippet. Absolutely awesome, thank you!

**Comment by casey** [comment]
@Matthias-Fauconneau Small improvement to the snippet:

```
cargo +nightly test --all --color always -- --color always 2>&1 | sed s/^O//g | bat --plain --paging always
```

`-- --color always` turns on colors in the test binaries, so test results are colored, not just compiler messages. `sed s/^O//g` strips a `^O` that the test binary appends to test results as part of its formatting. It needs to be the literal control character, not a caret followed by an uppercase O.

**Comment by Imberflur** [comment]
I've been using this snippet:
```sh
cargo watch -s 'cargo check --color always 2>&1 | bat -p --paging always'
```
but after a recent system update the old pager instance seems to no longer close automatically and I have to press `q` to see the next set of results 

edit: also updating cargo-watch itself fixed the issue!
