### ISSUE TITLE
Invoking cargo-watch directly should not require duplicate `watch`

### ISSUE THREAD

**Issue by moll** [passcod/cargo-watch#94]
Hey,

I used cargo-watch around a year or two ago and back then I could invoke it directly in the style of ./cargo/bin/cargo-watch build. I've now noticed it requires an extra `watch` to invoke --- `./cargo/bin/cargo-watch watch build`. Is that intentional or just a bug?

Git and other CLIs with external subcommands seem to work without subcommand duplication. That is, you can execute /usr/lib/git-core/git-log and get the log, not have to duplicate `log` there. I'd say cargo-watch should follow that pattern.

Thanks!

**Comment by passcod** [comment]
Intentional in that is a limitation of clap, which parses our arguments. A pull request to fix it would be accepted of course, but iirc at the time we couldn't find a straightforward way.

**Comment by moll** [comment]
Gotcha. Thank you for the quick response!

**Comment by moll** [comment]
Umm, shouldn't this be left open until it's actually addressed by whoever finds time this sunny summer? ;)

**Comment by passcod** [comment]
Ah, right. I'll blame that momentary lapse on the fact it's winter over here ;)
