### ISSUE TITLE
--clear doesn't work on MacOS (bash/iterm2)

### ISSUE THREAD

**Issue by behnam** [passcod/cargo-watch#99]
I used to use `cargo watch -c -x ....` commands frequently and it was working fine. But now trying it on my iterm2 I get a clear terminal on the first run, but not afterwards (between/in-start-of runs).

I don't know if it's an iterm2-configuration problem, or a `cargo-watch` issue. Are there any known issues? What should I look into to debug?

**Comment by passcod** [comment]
What does running `tput reset` do? That's what watchexec uses to clear the screen. Try running with `--debug` or replicating your setup with watchexec directly with the `--verbose` flag.

**Comment by behnam** [comment]
Thanks, @passcod. `tput reset` works fine and I cannot repro at the moment. I'll report back if/when I see it happen again.
